import { useEffect, useRef, useState } from "react";
import { Field } from "./App";
import Icon from "./Icon";
import { allenBradleyFamilies, allenBradleyFamilyName, defaultDeviceSettings, deviceMapBytes, deviceMapChanges, engineeringPointTypes, isLogixFamily, newDevicePoint, numericScalarTypes, parseDevicePointImport, pointAddressHint, pointStorageType, rawNumericPointTypes, stringCapacityLimit, validateDevicePoints, withAllenBradleyFamily } from "./deviceConnections";
import type { DeviceConnectionType, DevicePoint, DeviceSettings } from "./types";

export function DeviceConnectionFields({ type, settings, onChange }: { type: DeviceConnectionType; settings?: DeviceSettings; onChange: (settings: DeviceSettings) => void }) {
  const current = settings ?? defaultDeviceSettings(type), edit = (patch: Partial<DeviceSettings>) => onChange({ ...current, ...patch });
  return <>
    <div className="form-two-col"><Field label="Controller host"><input value={current.host} placeholder="192.168.1.10" onChange={event => edit({ host: event.target.value })} /></Field>
      <Field label={type === "beckhoff-ads" ? "ADS port" : "TCP port"} hint={type === "beckhoff-ads" ? "851 is the first TwinCAT 3 PLC runtime." : undefined}><input type="number" min={1} max={65535} value={current.port} onChange={event => edit({ port: Number(event.target.value) })} /></Field></div>
    {type === "modbus-tcp" && <Field label="Unit ID" hint="The device or downstream gateway unit identifier (0–255)."><input type="number" min={0} max={255} value={current.unitId ?? 1} onChange={event => edit({ unitId: Number(event.target.value) })} /></Field>}
    {type === "ab-eip" && <><div className="form-two-col"><Field label="Controller family"><select value={current.controllerFamily || "ControlLogix"} onChange={event => onChange(withAllenBradleyFamily(current, event.target.value))}>{allenBradleyFamilies.map(family => <option value={family} key={family}>{allenBradleyFamilyName(family)}</option>)}</select></Field>
      <Field label="CIP route" hint={isLogixFamily(current.controllerFamily) ? "Required port/slot route such as 1,0; use the route for this controller." : "This profile connects directly; the route must remain blank."}><input value={current.route || ""} disabled={!isLogixFamily(current.controllerFamily)} onChange={event => edit({ route: event.target.value })} /></Field></div>
      {isLogixFamily(current.controllerFamily) && <p className="muted">This profile supports numeric/Boolean symbols. String layouts require a verified controller schema and are outside this preview.</p>}
      {!isLogixFamily(current.controllerFamily) && <p className="muted">{current.controllerFamily === "Micro800" ? "Micro800, including Micro850 and Micro870, uses controller-scoped numeric/Boolean symbols and a direct connection. String layouts are outside this profile." : `This direct PCCC profile supports N/B words, Boolean N/B bits, F Float and ST String${current.controllerFamily === "MicroLogix" ? ", plus L Int32/UInt32" : ""}. N/B bits support Boolean reads and masked writes. DH+ routing and I/O, status, timer/counter files are outside this profile.`} Native browsing is unavailable for this family. Declare addresses in the register map.</p>}</>}
    {type === "siemens-s7" && <><Field label="CPU family"><select value={current.controllerFamily || "S71200"} onChange={event => edit({ controllerFamily: event.target.value })}>{["S7200", "S7300", "S7400", "S71200", "S71500"].map(family => <option key={family}>{family}</option>)}</select></Field>
      <div className="form-two-col"><Field label="Rack"><input type="number" min={0} max={255} value={current.rack ?? 0} onChange={event => edit({ rack: Number(event.target.value) })} /></Field><Field label="Slot"><input type="number" min={0} max={255} value={current.slot ?? 0} onChange={event => edit({ slot: Number(event.target.value) })} /></Field></div>
      <p className="muted">Use an accessible, non-optimized DB layout and the controller's permitted S7 communication settings.</p></>}
    {type === "beckhoff-ads" && <><div className="form-two-col"><Field label="Local AMS Net ID" hint="Six numbers separated by dots; identifies this gateway's ADS route."><input value={current.localAmsNetId || ""} placeholder="192.168.1.20.1.1" onChange={event => edit({ localAmsNetId: event.target.value })} /></Field><Field label="Target AMS Net ID"><input value={current.targetAmsNetId || ""} placeholder="192.168.1.10.1.1" onChange={event => edit({ targetAmsNetId: event.target.value })} /></Field></div><p className="muted">The controller needs a route back to this gateway. Test the saved connection to check the route and PLC runtime.</p></>}
    <Field label="Shared command domain (optional)" hint="Use the same name for connection aliases that reach the same physical controller, so their writes share a lock. Blank uses the controller host."><input value={current.contentionDomain || ""} onChange={event => edit({ contentionDomain: event.target.value })} /></Field>
    <Field label="Request timeout (ms)" hint="100–30,000 ms, including protocol request/response time."><input type="number" min={100} max={30000} step={100} value={current.timeoutMs ?? 2000} onChange={event => edit({ timeoutMs: Number(event.target.value) })} /></Field>
  </>;
}

export function DeviceRegisterMap({ type, controllerFamily, points, onChange, disabled, configurationKey = "" }: { type: DeviceConnectionType; controllerFamily?: string; points: DevicePoint[]; onChange: (points: DevicePoint[]) => void; disabled?: boolean; configurationKey?: string }) {
  const [pointDraft, setPointDraft] = useState<DevicePoint | null>(null), [editingId, setEditingId] = useState<string | null>(null);
  const [text, setText] = useState(""), [importOpen, setImportOpen] = useState(false), [error, setError] = useState("");
  const [preview, setPreview] = useState<{ origin: string; points: DevicePoint[] } | null>(null), [page, setPage] = useState(0);
  const pageSize = 50, currentPage = Math.min(page, Math.max(0, Math.ceil(points.length / pageSize) - 1)), rows = points.slice(currentPage * pageSize, (currentPage + 1) * pageSize);
  const origin = JSON.stringify({ type, controllerFamily: controllerFamily ?? null, points, configurationKey });
  const importRequest = useRef(0), mounted = useRef(false);
  const importContext = useRef({ origin, open: importOpen, disabled: Boolean(disabled) });
  if (importContext.current.origin !== origin || importContext.current.open !== importOpen || importContext.current.disabled !== Boolean(disabled)) {
    importRequest.current++;
    importContext.current = { origin, open: importOpen, disabled: Boolean(disabled) };
  }
  useEffect(() => {
    mounted.current = true;
    return () => { mounted.current = false; importRequest.current++; };
  }, []);
  const changes = preview ? deviceMapChanges(points, preview.points) : [], previewCurrent = preview?.origin === origin;
  const storageType = pointDraft ? pointStorageType(pointDraft) : undefined;
  const engineeringTypes = engineeringPointTypes(type, controllerFamily), rawTypes = rawNumericPointTypes(type, controllerFamily);
  const patch = (fields: Partial<DevicePoint>) => { if (pointDraft) { setPointDraft({ ...pointDraft, ...fields }); setError(""); } };
  function add() { let index = points.length + 1; while (points.some(point => point.id === `point${index}`)) index++; setEditingId(null); setPointDraft(newDevicePoint(type, index, controllerFamily)); setError(""); }
  function applyPoint() {
    if (!pointDraft) return;
    const next = editingId ? points.map(point => point.id === editingId ? pointDraft : point) : [...points, pointDraft], errors = validateDevicePoints(type, next, controllerFamily);
    if (errors.length) { setError(errors.join("\n")); return; }
    onChange(next); setPointDraft(null); setPreview(null);
  }
  function readMapFile(file?: File) {
    const request = ++importRequest.current, context = importContext.current;
    setPreview(null); setError("");
    if (!file) return;
    if (file.size > 2 * 1024 * 1024) { setError("Register-map JSON exceeds 2 MiB."); return; }
    const current = () => mounted.current && request === importRequest.current && context === importContext.current && context.open && !context.disabled;
    void file.text().then(value => {
      if (!current()) return;
      setText(value); setPreview(null); setError("");
    }).catch(reason => { if (current()) setError(String(reason)); });
  }
  return <div className="browse-section device-register-map"><div className="browse-section-heading"><div><h3>Register map</h3><p>Declare the points this gateway may read. Save the connection before browsing, reading or adding tags.</p></div><div className="editor-actions"><button className="button" disabled={disabled} onClick={add}><Icon name="plus" size={14} />Add point</button><button className="button" disabled={disabled} onClick={() => { importRequest.current++; setImportOpen(!importOpen); setPreview(null); setText(JSON.stringify(points, null, 2)); setError(""); }}>Import / edit JSON</button></div></div>
    <p className="muted">{pointAddressHint(type, controllerFamily)} Saved point IDs identify tag references; removal or incompatible changes may be blocked by those references. Map size: {(deviceMapBytes(points) / 1024).toFixed(1)} / 768 KiB, up to 10,000 points.</p>
    <fieldset disabled={disabled} style={{ border: 0, margin: 0, padding: 0 }}>
      {points.length > 0 && <div className="data-table-wrap"><table className="data-table"><thead><tr><th>Point</th><th>Address</th><th>Type</th><th>Access</th><th /></tr></thead><tbody>{rows.map(point => <tr key={point.id}><td><strong>{point.name}</strong><br /><small>{point.id}</small></td><td><code>{point.address}</code></td><td>{pointStorageType(point) === point.dataType ? point.dataType : `${pointStorageType(point)} raw → ${point.dataType}`}</td><td>{point.writable ? "Read / write" : "Read only"}</td><td><div className="editor-actions"><button className="button small" onClick={() => { setEditingId(point.id); setPointDraft({ ...point }); setError(""); }}>Edit</button><button className="button small danger" onClick={() => { onChange(points.filter(item => item.id !== point.id)); setPreview(null); if (editingId === point.id) setPointDraft(null); }}>Remove</button></div></td></tr>)}</tbody></table></div>}
      {points.length > pageSize && <div className="editor-actions"><button className="button small" disabled={currentPage === 0} onClick={() => setPage(currentPage - 1)}>Previous</button><span>{currentPage * pageSize + 1}–{Math.min((currentPage + 1) * pageSize, points.length)} of {points.length}</span><button className="button small" disabled={(currentPage + 1) * pageSize >= points.length} onClick={() => setPage(currentPage + 1)}>Next</button></div>}
      {!points.length && <p className="panel-empty">No points declared. Add a point or preview an imported map.</p>}
      {pointDraft && <div className="tag-mapping-form"><div><strong>{editingId ? "Edit point" : "New point"}</strong><button className="icon-button" aria-label="Cancel point changes" onClick={() => setPointDraft(null)}><Icon name="close" size={14} /></button></div>
        <div className="form-two-col"><Field label="Point ID" hint="Stable ID used by mapped tags."><input value={pointDraft.id} readOnly={Boolean(editingId)} onChange={event => patch({ id: event.target.value })} /></Field><Field label="Name"><input value={pointDraft.name} onChange={event => patch({ name: event.target.value })} /></Field></div>
        <Field label="Address" hint={pointAddressHint(type, controllerFamily)}><input value={pointDraft.address} onChange={event => patch({ address: event.target.value })} /></Field>
        <Field label="Engineering data type" hint="The type exposed by gateway tags after numeric scaling."><select value={pointDraft.dataType} onChange={event => patch({ dataType: event.target.value as DevicePoint["dataType"], ...(event.target.value === "String" ? { stringLength: type === "ab-eip" ? 82 : 80 } : {}), ...(["Boolean", "String"].includes(event.target.value) ? { rawDataType: null, scale: 1, offset: 0, byteSwap: false, wordSwap: false } : ["Boolean", "String"].includes(storageType ?? "") ? { rawDataType: null } : { rawDataType: pointDraft.rawDataType ?? pointDraft.dataType }) })}>{!engineeringTypes.includes(pointDraft.dataType) && <option value={pointDraft.dataType} disabled>{pointDraft.dataType} (unsupported)</option>}{engineeringTypes.map(dataType => <option key={dataType}>{dataType}</option>)}</select></Field>
        {numericScalarTypes.includes(pointDraft.dataType) && <Field label="Raw storage data type" hint="The controller's actual register or symbol encoding. For a UInt16 temperature scaled by 0.1, choose UInt16 raw and Double engineering."><select value={pointDraft.rawDataType ?? ""} onChange={event => patch({ rawDataType: event.target.value ? event.target.value as DevicePoint["dataType"] : null, ...(["Int16", "UInt16"].includes(event.target.value || pointDraft.dataType) ? { wordSwap: false } : {}) })}><option value="">Same as engineering type</option>{pointDraft.rawDataType && !rawTypes.includes(pointDraft.rawDataType) && <option value={pointDraft.rawDataType} disabled>{pointDraft.rawDataType} (unsupported)</option>}{rawTypes.map(dataType => <option key={dataType}>{dataType}</option>)}</select></Field>}
        {pointDraft.dataType === "String" && <Field label="String capacity (bytes)" hint={type === "siemens-s7" ? "S7 STRING capacity, excluding the two-byte header; maximum 254." : `Declared fixed text capacity, up to ${stringCapacityLimit(type, pointDraft.writable)} bytes. Reads and writes use this layout.`}><input type="number" min={1} max={stringCapacityLimit(type, pointDraft.writable)} value={pointDraft.stringLength ?? 80} onChange={event => patch({ stringLength: Number(event.target.value) })} /></Field>}
        {type === "modbus-tcp" && !["Boolean", "String"].includes(pointDraft.dataType) && <div className="form-two-col"><label className="checkbox-field"><input type="checkbox" checked={pointDraft.byteSwap ?? false} onChange={event => patch({ byteSwap: event.target.checked })} /><span>Swap bytes within each register</span></label><label className="checkbox-field"><input type="checkbox" checked={pointDraft.wordSwap ?? false} disabled={["Int16", "UInt16"].includes(storageType ?? "")} onChange={event => patch({ wordSwap: event.target.checked })} /><span>Reverse register word order</span></label></div>}
        {!["Boolean", "String"].includes(pointDraft.dataType) && <div className="form-two-col"><Field label="Scale" hint="Engineering value = raw × scale + offset."><input type="number" step="any" value={pointDraft.scale ?? 1} onChange={event => patch({ scale: Number(event.target.value) })} /></Field><Field label="Offset"><input type="number" step="any" value={pointDraft.offset ?? 0} onChange={event => patch({ offset: Number(event.target.value) })} /></Field></div>}
        <label className="checkbox-field"><input type="checkbox" checked={pointDraft.writable} onChange={event => patch({ writable: event.target.checked })} /><span>Allow reviewed scalar writes</span></label><p className="muted">Operators still need a published command and Commands permission. This editor does not write to equipment.</p>
        <div className="editor-actions"><button className="button" onClick={() => setPointDraft(null)}>Cancel</button><button className="button primary" onClick={applyPoint}>Apply point to draft</button></div>
      </div>}
      {importOpen && <div className="tag-mapping-form"><Field label="Import JSON file" hint="Choose a map up to 2 MiB, then validate and review the changes."><input type="file" accept=".json,application/json" onChange={event => readMapFile(event.target.files?.[0])} /></Field><Field label="Points JSON" hint='An array of objects with id, name, address, dataType and writable. Optional codecs: rawDataType, byteSwap, wordSwap, stringLength, scale and offset.'><textarea rows={12} spellCheck={false} value={text} onChange={event => { importRequest.current++; setText(event.target.value); setPreview(null); setError(""); }} /></Field><button className="button" onClick={() => { try { const imported = parseDevicePointImport(type, text, controllerFamily); setPreview({ origin, points: imported }); setError(""); } catch (reason) { setPreview(null); setError(reason instanceof Error ? reason.message : String(reason)); } }}>Validate and preview map</button>
        {preview && <><p role="status">{preview.points.length} points after apply · {changes.filter(change => change.action !== "Unchanged").length} changes. {previewCurrent ? "Review before applying to this draft." : "The map changed; preview again."}</p><div className="data-table-wrap" style={{ maxHeight: 260 }}><table className="data-table"><thead><tr><th>Action</th><th>ID</th><th>Name</th></tr></thead><tbody>{changes.filter(change => change.action !== "Unchanged").slice(0, 200).map(change => <tr key={change.id}><td>{change.action}</td><td>{change.id}</td><td>{change.name}</td></tr>)}</tbody></table></div>{changes.filter(change => change.action !== "Unchanged").length > 200 && <p>Showing the first 200 changes. Apply includes the complete map.</p>}<button className="button primary" disabled={!previewCurrent} onClick={() => { if (previewCurrent) { importRequest.current++; onChange(preview.points); setPreview(null); setPointDraft(null); setImportOpen(false); } }}>Apply reviewed map to draft</button></>}
      </div>}
    </fieldset>{error && <p className="inline-error" role="alert" style={{ whiteSpace: "pre-wrap" }}>{error}</p>}
  </div>;
}
