import type { EventScriptLanguage } from "./eventScriptAuthoring";

export default function EventScriptLanguagePicker({ language, pythonAvailable = true, restriction = "This event supports browser JavaScript only.", onChange }: {
  language: EventScriptLanguage; pythonAvailable?: boolean; restriction?: string; onChange: (language: EventScriptLanguage) => void;
}) {
  return <div className="event-script-language"><label>Language<select aria-label="Event script language" value={language} onChange={event => onChange(event.target.value as EventScriptLanguage)}>
    {pythonAvailable && <option value="python">Python 3 · gateway</option>}<option value="javascript">JavaScript · browser</option>
  </select></label><p>{pythonAvailable ? "Switching languages keeps a separate draft for each; it does not translate code. Only the selected language is applied." : restriction}</p>
    {language === "python" && <p>Check syntax compiles Python on the gateway without running code. Use Live Preview to test runtime behavior. Read-only Preview does not run Python events.</p>}
  </div>;
}

export function PythonEventContext({ cleanup = false, buttonAction = false, password = false }: { cleanup?: boolean; buttonAction?: boolean; password?: boolean } = {}) {
  return <><h4>Python component context</h4>{cleanup ? <><p><code>{password ? "self.enabled" : "self.text"}</code>, <code>self.getSibling("heading-id").text</code> and <code>self.parent.custom.title</code> read the captured component and local-state snapshot. Use component IDs, not captions.</p><p>Unmount is cleanup only. Assigning component properties, form values or local UI state is rejected. Use <code>print()</code> or a logger for cleanup diagnostics; no UI effects are applied to the closed context.</p></> : <><p><code>{password ? "self.enabled = True" : 'self.text = "hi"'}</code> changes this component. Use <code>self.getSibling("heading-id").text = "Ready"</code> to update another component in this form; use its ID, not its caption.</p><p><code>self.parent.custom.title = "Ready"</code> updates declared screen state, or this template's private state. Update the source of a bound property instead of assigning over its binding.</p></>}
    <h4>Form values</h4><p><code>self.getSibling("field-id").value</code> reads a non-password field's captured value. {cleanup ? "Cleanup cannot assign form values." : <>Assign a typed value to an unbound, writable field to update it after success. Programmatic writes do not fire change or commit events. State, tag, expression, query, dynamic-option and selection bindings remain authoritative; update their source instead.</>} Password text and values are unavailable through component properties.</p>
    <h4>Local and shared changes</h4><p>Python runs on the gateway. {cleanup ? "The closed UI cannot be changed." : "UI changes apply together after success in this receiving session only."} A tag write or named-query update changes shared data for other sessions bound to it. Shared writes are not rolled back if a later statement fails.</p>
    <h4>Messages</h4><p><code>system.ui.sendMessage("refresh", {"{}"})</code> reaches matching session-scope handlers in this project's active operator tabs. Use <code>system.ui.getSessionInfo()</code> and the optional <code>sessionId</code> argument to target one tab. <code>system.util.sendMessage</code> and <code>sendRequest</code> call published gateway message resources.</p>
    <p>Python requires operator permission in the runtime or administrator-enabled Live Preview. {buttonAction ? "Button actions validate and submit the whole form, including password inputs; access them only through inputs. Button actions do not receive an automatic event payload." : "Automatic events omit password values and do not require the whole form to be complete."} {buttonAction ? "Use print() for execution output and result for a returned message." : "Gateway execution has a 2-second limit; the browser allows 3 seconds for the response, including transport."} Scripts are trusted gateway code.{!cleanup && <> Use <code>result = {"{\"message\": \"Updated\"}"}</code> for a result message.</>}</p></>;
}
