import { useState } from "react";
import type { ModelGroup, ModelPackage } from "./modelWorkspace";

export default function ModelWorkspaceSettings({ model, onChange }: { model: ModelPackage; onChange: (next: ModelPackage) => void }) {
  const [selected, setSelected] = useState("provider"), [remove, setRemove] = useState(false);
  const group = model.scanGroups.find(item => item.name === selected);
  const provider = model.provider || { name: "default", enabled: true, requireDeclaredHierarchy: false };
  function patch(next: Partial<ModelGroup>) {
    if (!group) return;
    onChange({ ...model, scanGroups: model.scanGroups.map(item => item === group ? { ...group, ...next } : item) });
    if (next.name !== undefined) setSelected(next.name);
  }
  function add() {
    let name = "NewGroup", suffix = 2; while (model.scanGroups.some(item => item.name === name)) name = `NewGroup${suffix++}`;
    onChange({ ...model, scanGroups: [...model.scanGroups, { name, publishingIntervalMs: 1000, enabled: true }] }); setSelected(name);
  }
  return <><div className="model-section-intro"><h2>Keep your data up to date</h2><p>These settings affect every project on this gateway. Leave the defaults in place unless you need different update timing.</p></div><div className="model-settings-layout"><aside aria-label="Model settings"><button type="button" className={`button ${selected === "provider" ? "active" : ""}`} onClick={() => { setSelected("provider"); setRemove(false); }}>Gateway data</button><div className="model-actions"><strong>Update groups</strong><button type="button" className="button small" disabled={model.scanGroups.length >= 32} onClick={add}>Add group</button></div><p className="model-field-help">Tags in the same group share an update interval. These are also called scan groups.</p>{model.scanGroups.map(item => <button type="button" key={item.name} className={`button ${selected === item.name ? "active" : ""}`} onClick={() => { setSelected(item.name); setRemove(false); }}>{item.name} <small>{item.publishingIntervalMs} ms</small></button>)}</aside>
    <section className="model-editor">{selected === "provider" ? <><h3>Gateway data</h3><p>The <code>[default]</code> provider holds the tags shared by your projects.</p><label className="model-checkbox"><input type="checkbox" checked={provider.enabled} onChange={event => onChange({ ...model, provider: { ...provider, enabled: event.target.checked } })} />Keep data collection running</label><p className="model-field-help">Turning this off stops collection and marks tag values unavailable after you apply the change.</p><label className="model-checkbox"><input type="checkbox" checked={provider.requireDeclaredHierarchy === true} onChange={event => onChange({ ...model, provider: { ...provider, requireDeclaredHierarchy: event.target.checked } })} />Require a location for every equipment instance</label><p className="model-field-help">Open Plant and choose Add location, then place your machines inside it.</p><p>Changes here join the same review as your models and equipment.</p></> : group && <><h3>Update group</h3><div className="model-grid"><label>Group name<input value={group.name} onChange={event => patch({ name: event.target.value })} /></label><label>Update interval (ms)<input type="number" min={100} max={60000} step={100} value={group.publishingIntervalMs} onChange={event => patch({ publishingIntervalMs: Number(event.target.value) })} /><span className="model-field-help">1,000 ms = once a second.</span></label></div><label className="model-checkbox"><input type="checkbox" checked={group.enabled !== false} onChange={event => patch({ enabled: event.target.checked })} />Update this group</label><p>Choose how often this group collects data. The review shows which tags your changes affect.</p><button type="button" className="button danger" onClick={() => setRemove(true)}>Remove group</button>{remove && <div role="alert" className="model-card"><p>Remove {group.name}? Tags using this group will need another group before you can apply.</p><div className="model-actions"><button type="button" className="button" onClick={() => setRemove(false)}>Keep group</button><button type="button" className="button danger" onClick={() => { onChange({ ...model, scanGroups: model.scanGroups.filter(item => item !== group) }); setSelected("provider"); setRemove(false); }}>Remove group</button></div></div>}</>}</section></div></>;
}
