import { useId, useRef } from "react";
import type { Connection } from "./types";
import { ModelSourceFields } from "./modelWorkspaceTypes";
import { ModelPairs, ModelScalarField } from "./modelWorkspaceFields";
import { modelDataTypes, type ModelDefinition, type ModelMember, type ModelPackage, type ModelParameter } from "./modelWorkspace";
import type { ModelSourceTag } from "./modelBuilderOperations";
import { acceptsBuilderDrag } from "./modelBuilderLibrary";
import { ModelContractFields, ModelSemanticField, ModelUnitField, ModelUnitSystemField } from "./modelContractFields";
import { modelParameterNamePattern } from "./modelParameterRules";
import "./modelFieldEditor.css";

const memberDescription = (kind: ModelMember["kind"]) => ({ reference: "A field linked to an existing tag.", memory: "A value stored on the gateway.", expression: "A value calculated from other data.", type: "A group of fields from another model.", opcua: "A field read directly from an OPC UA connection.", device: "A field read directly from a device connection." })[kind];
type MemberProps = { value: ModelMember; definition: ModelDefinition; model: ModelPackage; connections: Connection[]; tags: ModelSourceTag[]; readOnly: boolean; onChange: (member: ModelMember) => void; onRemove: () => void };
export function BuilderMemberEditor(props: MemberProps) {
  const { value, onChange, readOnly } = props, patch = (next: Partial<ModelMember>) => onChange({ ...value, ...next });
  return <><p className="model-help">{memberDescription(value.kind)} {readOnly ? "Edit a new model version to change this field." : "Your edits stay in the draft until review."}</p><fieldset disabled={readOnly} className="model-drawer-fields model-simple-field-editor">
    <label>Name<input value={value.path} onChange={event => patch({ path: event.target.value })} /><small>Use a slash to place a field in a group, for example Motor/Speed.</small></label>
    <BuilderMemberSource {...props} onPatch={patch} />
    {value.kind !== "type" && <><label>Type{value.kind === "reference" ? <input readOnly value={value.dataType || "Unknown"} /> : <select value={value.dataType || "Double"} onChange={event => patch({ dataType: event.target.value })}>{modelDataTypes.map(type => <option key={type}>{type}</option>)}</select>}{value.kind === "reference" && <small>Uses the type of the tag you selected.</small>}</label><BuilderMemberMetadata {...props} onPatch={patch} /></>}
    <label className="model-checkbox"><input type="checkbox" checked={value.enabled !== false} onChange={event => patch({ enabled: event.target.checked })} />Field enabled</label></fieldset>
    <button type="button" className="button danger" disabled={readOnly} onClick={props.onRemove}>Remove field</button></>;
}
function BuilderMemberMetadata({ value, model, onPatch }: MemberProps & { onPatch: (patch: Partial<ModelMember>) => void }) {
  return <><ModelUnitField value={value} onChange={onPatch} compact /><label>Description<input maxLength={2048} value={value.description || ""} placeholder="What does this value tell someone?" onChange={event => onPatch({ description: event.target.value || undefined })} /></label><ModelContractFields value={value} onChange={onPatch} includeSemantic={false} />
    <details className="model-contract-section"><summary>Advanced metadata</summary><ModelUnitSystemField value={value} onChange={onPatch} /><ModelSemanticField value={value} onChange={onPatch} /><label>Meaning category<input maxLength={128} value={value.semanticType || ""} placeholder="Optional semantic type" onChange={event => onPatch({ semanticType: event.target.value || undefined })} /></label><ModelPairs label="Attributes" value={value.attributes} onChange={attributes => onPatch({ attributes })} /></details>
    {value.kind !== "reference" && <details className="model-contract-section"><summary>Sampling options</summary><p>These settings control how often this field updates. Leave the defaults unless your source needs different timing.</p>{(["memory", "opcua", "device"] as string[]).includes(value.kind) && <label>Scan group<select value={value.scanGroup || ""} onChange={event => onPatch({ scanGroup: event.target.value || undefined })}><option value="">Default scan</option>{model.scanGroups.map(group => <option key={group.name}>{group.name}</option>)}</select></label>}{(["expression", "opcua", "device"] as string[]).includes(value.kind) && <label>Update interval (ms)<input type="number" min={100} max={60000} value={value.publishingIntervalMs ?? 1000} onChange={event => onPatch({ publishingIntervalMs: Number(event.target.value) })} /></label>}</details>}</>;
}
function BuilderMemberSource({ value, definition, tags, model, connections, onPatch }: MemberProps & { onPatch: (patch: Partial<ModelMember>) => void }) {
  if (value.kind === "reference") return <><BuilderTagInput label="Read from" value={value.target || ""} tags={tags} parameters={definition.parameters || []} onChange={target => { const source = tags.find(tag => tag.path === target); onPatch({ target, ...(source ? { dataType: source.dataType || source.liveDataType || value.dataType } : {}) }); }} /><small>This field shows the value of an existing tag. It uses that tag’s data type and cannot write back. Parameters choose the matching tag for each machine.</small></>;
  if (value.kind === "expression") return <><p className="model-help">Calculate a value from other fields or tags. Add each input below, then use its name in the expression.</p><label>Expression<textarea rows={3} value={value.expression || ""} onChange={event => onPatch({ expression: event.target.value })} /></label><BuilderInputs value={value.inputs || {}} onChange={inputs => onPatch({ inputs })} tags={tags} definition={definition} /></>;
  return <ModelSourceFields value={value} onChange={onPatch} model={model} connections={connections} tagPaths={[]} />;
}
export function BuilderTagInput({ label, value, onChange, tags, parameters, extra = [] }: { label: string; value: string; onChange: (value: string) => void; tags: ModelSourceTag[]; parameters: ModelParameter[]; extra?: string[] }) {
  const id = useId(), input = useRef<HTMLInputElement>(null);
  const matches = [...extra, ...tags.filter(tag => !value || value.includes("{") || tag.path.toLowerCase().includes(value.toLowerCase())).slice(0, 100).map(tag => tag.path)].slice(0, 100);
  function insert(name: string) { if (!name) return; const start = input.current?.selectionStart ?? value.length, end = input.current?.selectionEnd ?? start; onChange(value.slice(0, start) + `{${name}}` + value.slice(end)); input.current?.focus(); }
  return <div className="model-tag-input" onDragOver={event => { if (acceptsBuilderDrag(event, ["tag"])) { event.preventDefault(); event.stopPropagation(); } }} onDrop={event => { const path = event.dataTransfer.getData("text/spark-tag"); if (path) { event.preventDefault(); event.stopPropagation(); onChange(path); } }}><label>{label}<input ref={input} list={id} value={value} onChange={event => onChange(event.target.value)} placeholder="Search a tag path, or drop a tag here" /></label><datalist id={id}>{matches.map(path => <option key={path} value={path} />)}</datalist>{parameters.length > 0 && <select aria-label={`Insert parameter into ${label}`} value="" onChange={event => insert(event.target.value)}><option value="">Insert parameter…</option>{parameters.map(parameter => <option key={parameter.name} value={parameter.name}>{`{${parameter.name}}`}</option>)}</select>}</div>;
}
function BuilderInputs({ value, onChange, tags, definition }: { value: Record<string, string>; onChange: (value: Record<string, string>) => void; tags: ModelSourceTag[]; definition: ModelDefinition }) {
  const members = definition.members.filter(member => member.kind !== "type").map(member => `./${member.path}`);
  return <section className="model-expression-inputs"><h4>Inputs</h4>{Object.entries(value).map(([name, target], index) => <div className="model-input-slot" key={index}><label>Input name<input value={name} onChange={event => onChange(Object.fromEntries(Object.entries(value).map(([key, path]) => [key === name ? event.target.value : key, path])))} /></label><BuilderTagInput label={`Target for ${name || "new input"}`} value={target} tags={tags} parameters={definition.parameters || []} extra={members} onChange={path => onChange({ ...value, [name]: path })} /><button type="button" className="button small danger" onClick={() => onChange(Object.fromEntries(Object.entries(value).filter(([key]) => key !== name)))}>Remove input</button></div>)}<button type="button" className="button small" disabled={Object.keys(value).length >= 32 || Object.hasOwn(value, "")} onClick={() => onChange({ ...value, "": "" })}>Add input</button></section>;
}
export function BuilderParameterEditor({ value, readOnly, onChange, onRemove }: { value: ModelParameter; readOnly: boolean; onChange: (parameter: ModelParameter) => void; onRemove: () => void }) {
  return <><p>A parameter is a value you fill in for each machine. For example, use <code>{`{${value.name}}`}</code> in a tag path, then set it to Press01 or Press02 for each piece of equipment.</p><fieldset disabled={readOnly} className="model-drawer-fields"><label>Parameter name<input value={value.name} pattern={modelParameterNamePattern.source} onChange={event => onChange({ ...value, name: event.target.value })} /></label><label>Type<select value={value.type} onChange={event => onChange({ ...value, type: event.target.value as ModelParameter["type"], default: undefined })}>{["String", "Double", "Int64", "Boolean"].map(type => <option key={type}>{type}</option>)}</select></label><label className="model-checkbox"><input type="checkbox" checked={value.required === true} onChange={event => onChange({ ...value, required: event.target.checked })} />Ask for a value for each machine</label><label className="model-checkbox"><input type="checkbox" checked={value.default !== undefined} onChange={event => onChange({ ...value, default: event.target.checked ? value.type === "String" ? "" : value.type === "Boolean" ? false : 0 : undefined })} />Use a default when left blank</label>{value.default !== undefined && <ModelScalarField label="Default" value={value.default} type={value.type} onChange={next => onChange({ ...value, default: next })} />}</fieldset><button type="button" className="button danger" disabled={readOnly} onClick={onRemove}>Remove parameter</button></>;
}
