import { useEffect, useState } from "react";
import { getModelObject, modelLeaves, type ModelObject } from "./modelApi";
import { getModelIssues, modelErrorText, type ModelIssue, type ModelIssuePage } from "./modelOperationsApi";
import type { ModelPackage } from "./modelWorkspace";
import { modelIssueLabel, modelQualityLabel } from "./modelReadiness";
import "./modelReadiness.css";

export function ModelIssuesPanel({ model, onNavigate, initialEquipment }: { model: ModelPackage; onNavigate: (path: string) => void; initialEquipment?: string }) {
  const [path, setPath] = useState(initialEquipment || ""), [offset, setOffset] = useState(0), [revision, setRevision] = useState(0), [page, setPage] = useState<ModelIssuePage>(), [error, setError] = useState("");
  useEffect(() => { if (initialEquipment !== undefined) { setPath(initialEquipment); setOffset(0); } }, [initialEquipment]);
  useEffect(() => { const controller = new AbortController(); setPage(undefined); setError(""); void getModelIssues(path, offset, controller.signal).then(setPage).catch(reason => { if (!controller.signal.aborted) setError(modelErrorText(reason)); }); return () => controller.abort(); }, [path, offset, revision]);
  return <section className="model-operation-panel"><header><div><h2>Data issues</h2><p>Find measurements that are out of range, stale or outside their allowed values. Process alarms remain in the gateway Alarms view.</p></div><button type="button" className="button" onClick={() => setRevision(value => value + 1)}>Refresh issues</button></header><label>Equipment<select value={path} onChange={event => { setPath(event.target.value); setOffset(0); }}><option value="">All equipment</option>{model.instances.map(item => <option key={item.path}>{item.path}</option>)}</select></label>{error && <p className="security-error" role="alert">{error}</p>}{!page && !error && <p role="status">Loading data issues…</p>}{page && <><p role="status">{page.total ? `${page.total} data issues · showing ${offset + 1}–${offset + page.items.length}` : "No model rule violations found. Live values also show connection and data quality problems."}</p><div className="model-operation-list">{page.items.map((issue, index) => <ModelIssueCard key={`${issue.path}:${issue.code}:${index}`} issue={issue} onNavigate={onNavigate} />)}</div><div className="model-actions"><button type="button" className="button" disabled={!offset} onClick={() => setOffset(Math.max(0, offset - 100))}>Previous</button><button type="button" className="button" disabled={offset + page.items.length >= page.total} onClick={() => setOffset(offset + 100)}>Next</button></div></>}</section>;
}
function ModelIssueCard({ issue, onNavigate }: { issue: ModelIssue; onNavigate: (path: string) => void }) {
  const equipment = issue.instancePath.slice(Math.max(issue.instancePath.lastIndexOf("/"), issue.instancePath.indexOf("]")) + 1);
  return <article className="model-card"><div className="model-actions"><strong>{equipment} · {issue.modelPath || "Field"}</strong><span className="model-status-pill degraded">{modelIssueLabel(issue.code)}</span><button type="button" className="button small" onClick={() => onNavigate(issue.instancePath)}>Open equipment</button></div><p>{issue.message}</p><dl className="model-facts"><dt>Original value</dt><dd className="model-issue-value">{JSON.stringify(issue.value)}</dd><dt>Expected</dt><dd>{issue.expected}</dd>{issue.receiptTimestamp && <><dt>Last sample</dt><dd>{new Date(issue.receiptTimestamp).toLocaleString()}</dd></>}</dl><details className="model-issue-details"><summary>Technical details</summary><dl className="model-facts"><dt>Equipment path</dt><dd><code>{issue.instancePath}</code></dd><dt>Field path</dt><dd><code>{issue.path}</code></dd><dt>Issue code</dt><dd><code>{issue.code}</code></dd><dt>Modeled quality</dt><dd><code>{issue.quality}</code></dd><dt>Source quality</dt><dd><code>{issue.sourceQuality}</code></dd>{issue.target && <><dt>Source tag</dt><dd><code>{issue.target}</code></dd></>}</dl></details></article>;
}
export function ModelLiveObjectPanel({ model, initialEquipment }: { model: ModelPackage; initialEquipment?: string }) {
  const [path, setPath] = useState(initialEquipment || model.instances[0]?.path || ""), [object, setObject] = useState<ModelObject>(), [error, setError] = useState(""), [revision, setRevision] = useState(0), [json, setJson] = useState(false);
  useEffect(() => { if (initialEquipment !== undefined) setPath(initialEquipment); }, [initialEquipment]);
  useEffect(() => { setObject(undefined); setError(""); if (!path) return; const controller = new AbortController(); void getModelObject(path, controller.signal).then(setObject).catch(reason => { if (!controller.signal.aborted) setError(modelErrorText(reason)); }); return () => controller.abort(); }, [path, revision]);
  return <section className="model-operation-panel"><header><div><h2>Live values</h2><p>Inspect saved equipment with its values, timestamps and quality. Apply the draft before checking its runtime result.</p></div><button type="button" className="button" disabled={!path} onClick={() => setRevision(value => value + 1)}>Refresh values</button></header><label>Saved equipment<select value={path} onChange={event => setPath(event.target.value)}><option value="">Choose equipment…</option>{model.instances.map(item => <option key={item.path}>{item.path}</option>)}</select></label>{error && <p className="security-error" role="alert">{error}</p>}{object && <><label className="model-checkbox"><input type="checkbox" checked={json} onChange={event => setJson(event.target.checked)} />Show JSON</label>{json ? <pre className="model-json-preview">{JSON.stringify(object, null, 2)}</pre> : <div className="model-table-wrap"><table><thead><tr><th>Field</th><th>Value</th><th>Status</th><th>Received</th></tr></thead><tbody>{modelLeaves(object.members).map(leaf => <tr key={leaf.path}><td>{leaf.modelPath}</td><td>{JSON.stringify(leaf.value)}</td><td><span title={leaf.quality}>{/^Good/i.test(leaf.quality) ? "Good data" : !leaf.receiptTimestamp && ["Bad_WaitingForInitialData", "Bad_NoData"].includes(leaf.quality) ? "Waiting for data" : modelQualityLabel(leaf.quality)}</span></td><td>{leaf.receiptTimestamp ? new Date(leaf.receiptTimestamp).toLocaleString() : "Waiting"}</td></tr>)}</tbody></table></div>}</>}</section>;
}
