import { useEffect, useRef, useState } from "react";
import { definitionKey, bulkModelInstances, upgradeModelInstances, modelLeaves, modelScalar, emptyModelPackage, type ModelDefinition, type ModelInstance, type ModelMember, type ModelPackage } from "./modelWorkspace";
import { ModelAlarmFields, ModelEnumField } from "./modelContractFields";
import { ModelPairs, ModelParameterValues } from "./modelWorkspaceFields";

const overrideFields = (member: ModelMember) => [...(member.kind === "memory" ? ["value"] : member.kind === "reference" ? ["target"] : member.kind === "expression" ? ["expression", "inputs"] : ["connectionId", "nodeId", "absoluteDeadband", "queueSize"]), "enabled", ...(member.kind === "reference" ? [] : ["scanGroup", "publishingIntervalMs"]), "description", "unit", "unitSystem", "semanticType", "semanticId", "freshnessMs", "enumValues", "alarms", "attributes", ...(["String", "Boolean"].includes(member.dataType || "String") ? [] : ["range"])];
const overrideDefaults: Record<string, unknown> = { enabled: true, alarms: [], enumValues: [], freshnessMs: 0, unitSystem: "custom", inputs: {}, attributes: {}, range: { low: 0, high: 100 }, absoluteDeadband: 0, queueSize: 1, publishingIntervalMs: 1000 };
const overrideDefault = (field: string) => structuredClone(overrideDefaults[field] ?? "");
function OverrideValue({ field, member, value, onChange }: { field: string; member: ModelMember; value: unknown; onChange: (value: unknown) => void }) {
  if (field === "alarms") return <ModelAlarmFields value={value as ModelMember["alarms"]} onChange={onChange} />;
  if (field === "enumValues") return <ModelEnumField value={value as ModelMember["enumValues"]} dataType={member.dataType} onChange={next => onChange(next || [])} />;
  if (field === "unitSystem") return <select aria-label={`${member.path} unit system`} value={String(value)} onChange={event => onChange(event.target.value)}><option value="custom">Custom</option><option value="ucum">UCUM</option></select>;
  if (field === "inputs") return <ModelPairs label="Override inputs" stringsOnly value={value as Record<string, string>} onChange={onChange} />;
  if (field === "attributes") return <ModelPairs label="Override attributes" value={value as Record<string, string>} onChange={onChange} />;
  if (field === "range") { const range = value as { low: number; high: number }; return <div className="model-grid"><label>Override low<input type="number" value={range.low} onChange={event => onChange({ ...range, low: Number(event.target.value) })} /></label><label>Override high<input type="number" value={range.high} onChange={event => onChange({ ...range, high: Number(event.target.value) })} /></label></div>; }
  if (field === "enabled") return <select aria-label={`${member.path} ${field}`} value={String(value)} onChange={event => onChange(event.target.value === "true")}><option value="true">Enabled</option><option value="false">Disabled</option></select>;
  const type = field === "value" ? member.dataType : ["publishingIntervalMs", "absoluteDeadband", "queueSize", "freshnessMs"].includes(field) ? "Double" : "String";
  return <input aria-label={`${member.path} ${field}`} value={value == null ? "" : String(value)} onChange={event => onChange(modelScalar(event.target.value, type || "String"))} />;
}
export function ModelOverrides({ value, onChange, definition, definitions }: { value: ModelInstance; onChange: (value: ModelInstance) => void; definition: ModelDefinition; definitions: ModelDefinition[] }) {
  const [filter, setFilter] = useState("");
  const leaves = modelLeaves(definition, definitions), overrides = value.overrides || {};
  function setField(path: string, field: string, next: unknown, remove = false) {
    const patch = { ...overrides[path], [field]: next } as Record<string, unknown>; if (remove) delete patch[field];
    const all = { ...overrides }; if (Object.keys(patch).length) all[path] = patch; else delete all[path]; onChange({ ...value, overrides: all });
  }
  const stale = Object.keys(overrides).filter(path => !leaves.some(member => member.path === path));
  return <section><h3>Member overrides</h3><p>Unchecked fields inherit the parameter-substituted definition. An explicit override wins over parameters. Nested members use their full relative path.</p><label>Find member<input value={filter} onChange={event => setFilter(event.target.value)} /></label>
    {stale.map(path => <p className="model-warning" key={path}>Override no longer has a member: {path} <button type="button" className="button" onClick={() => onChange({ ...value, overrides: Object.fromEntries(Object.entries(overrides).filter(([key]) => key !== path)) })}>Remove stale override</button></p>)}
    {leaves.filter(member => member.path.toLowerCase().includes(filter.toLowerCase())).map(member => <details className="model-card" key={member.path}><summary>{member.path} · {Object.keys(overrides[member.path] || {}).length} overrides</summary>{overrideFields(member).map(field => {
      const source = member as unknown as Record<string, unknown>, patch = overrides[member.path] as Record<string, unknown> | undefined, checked = Boolean(patch && Object.hasOwn(patch, field));
      return <div className="model-override" key={field}><label className="model-checkbox"><input type="checkbox" checked={checked} onChange={event => setField(member.path, field, source[field] ?? overrideDefault(field), !event.target.checked)} />{field}</label>{checked ? <OverrideValue field={field} member={member} value={patch![field]} onChange={next => setField(member.path, field, next)} /> : <span className="muted">Inherited · {typeof source[field] === "object" ? "configured value" : String(source[field] ?? "default")}</span>}</div>;
    })}</details>)}
  </section>;
}
export function ModelInstanceEditor({ value, onChange, model, saved }: { value: ModelInstance; onChange: (value: ModelInstance) => void; model: ModelPackage; saved: boolean }) {
  const definition = model.udtDefinitions.find(item => item.id === value.definitionId && item.version === value.version);
  return <section className="model-editor" aria-label="Instance editor"><div className="model-grid"><label>Instance path<input readOnly={saved} value={value.path} placeholder="[default]Acme/Site/Area/Line/CNC01" onChange={event => onChange({ ...value, path: event.target.value })} /></label><label>Pinned type version<select value={definition ? definitionKey(definition) : ""} onChange={event => { const next = model.udtDefinitions.find(item => definitionKey(item) === event.target.value); if (next) onChange({ ...value, definitionId: next.id, version: next.version }); }}><option value="">Choose a saved type…</option>{model.udtDefinitions.map(item => <option key={definitionKey(item)}>{definitionKey(item)}</option>)}</select></label></div>
    <label className="model-checkbox"><input type="checkbox" checked={value.enabled !== false} onChange={event => onChange({ ...value, enabled: event.target.checked })} />Instance enabled</label>
    {definition && <><label>Source mapping profile<select value={value.mappingProfileId || ""} onChange={event => onChange({ ...value, mappingProfileId: event.target.value || undefined })}><option value="">Sources from model definition</option>{(model.mappingProfiles || []).filter(profile => profile.definitionId === value.definitionId && profile.version === value.version).map(profile => <option key={profile.id}>{profile.id}</option>)}</select></label><h3>Instance parameters</h3><ModelParameterValues parameters={definition.parameters || []} values={value.parameters} onChange={parameters => onChange({ ...value, parameters })} /><ModelOverrides value={value} onChange={onChange} definition={definition} definitions={model.udtDefinitions} /></>}
  </section>;
}
export function ModelBulkEditor({ model, csv, onCsv, invalidate, onPreview }: { model: ModelPackage; csv: string; onCsv: (csv: string) => void; invalidate: () => void; onPreview: (package_: ModelPackage) => Promise<void> }) {
  const fileGeneration = useRef(0);
  useEffect(() => () => { fileGeneration.current++; }, []);
  const [mode, setMode] = useState("csv"), [type, setType] = useState(""), [selected, setSelected] = useState<string[]>([]), [filter, setFilter] = useState(""), [error, setError] = useState("");
  const definition = model.udtDefinitions.find(item => definitionKey(item) === type), matches = model.instances.filter(item => item.definitionId === definition?.id && item.path.includes(filter));
  async function preview() { try { setError(""); const instances = mode === "csv" ? bulkModelInstances(csv, model.udtDefinitions, model.instances) : upgradeModelInstances(model.instances, selected, definition!); await onPreview({ ...emptyModelPackage(), instances }); } catch (reason) { setError(reason instanceof Error ? reason.message : String(reason)); } }
  async function file(file?: File) { if (!file) return; const stamp = ++fileGeneration.current; try { if (file.size > 32 * 1024 * 1024) throw new Error("CSV files are limited to 32 MiB."); const next = await file.text(); if (stamp === fileGeneration.current) { onCsv(next); setError(""); } } catch (reason) { if (stamp === fileGeneration.current) setError(String(reason)); } }
  return <section className="model-editor" aria-label="Bulk instances"><div className="model-actions"><button type="button" className="button" aria-pressed={mode === "csv"} onClick={() => { setMode("csv"); invalidate(); }}>Instantiate from CSV</button><button type="button" className="button" aria-pressed={mode === "upgrade"} onClick={() => { setMode("upgrade"); invalidate(); }}>Upgrade selected instances</button></div>
    {mode === "csv" ? <><p>Columns: <code>path,definitionId,version,&lt;parameter names&gt;</code>. Up to 2,000 rows. Blank parameter cells use the type default or omit the value. Existing paths are reported as collisions; edit or upgrade those instances separately.</p><label>CSV file<input type="file" accept=".csv,text/csv" onChange={event => { void file(event.target.files?.[0]); event.target.value = ""; }} /></label><label>Instance CSV<textarea rows={10} spellCheck={false} value={csv} onChange={event => { fileGeneration.current++; onCsv(event.target.value); }} placeholder={'path,definitionId,version,Device\n[default]Plant/Line/CNC01,CNC,1,Haas01'} /></label></> : <><label>Upgrade to type version<select value={type} onChange={event => { setType(event.target.value); setSelected([]); invalidate(); }}><option value="">Choose version…</option>{model.udtDefinitions.map(item => <option key={definitionKey(item)}>{definitionKey(item)}</option>)}</select></label><label>Filter instance path<input value={filter} onChange={event => setFilter(event.target.value)} /></label><div className="model-actions"><button type="button" className="button" onClick={() => { setSelected(matches.map(item => item.path)); invalidate(); }}>Select all {matches.length} matching instances</button><button type="button" className="button" onClick={() => { setSelected([]); invalidate(); }}>Clear selection</button><span>{selected.length} selected · parameters and overrides retained</span></div><div className="model-bulk-list">{matches.map(item => <label className="model-checkbox" key={item.path}><input type="checkbox" checked={selected.includes(item.path)} onChange={event => { setSelected(event.target.checked ? [...selected, item.path] : selected.filter(path => path !== item.path)); invalidate(); }} />{item.path} · v{item.version}</label>)}</div></>}
    {error && <p role="alert" className="security-error">{error}</p>}<button type="button" className="button" disabled={mode === "upgrade" && (!definition || !selected.length)} onClick={() => void preview()}>Preview all instances</button>
  </section>;
}
