import { useEffect, useId, useState } from "react";
import { api } from "./api";
import { modelScalar, type ModelAlarm, type ModelMember, type ModelMetadata, type ModelScalar } from "./modelWorkspace";

export function ModelUnitSystemField({ value, onChange }: { value: ModelMetadata; onChange: (patch: Partial<ModelMetadata>) => void }) {
  return <label>Unit validation<select value={value.unitSystem || "custom"} onChange={event => onChange({ unitSystem: event.target.value as "custom" | "ucum" })}><option value="custom">Allow my own unit label</option><option value="ucum">Check against supported standard units (UCUM)</option></select><small>Choose standard units when another system needs a consistent unit code.</small></label>;
}
export function ModelSemanticField({ value, onChange }: { value: ModelMetadata; onChange: (patch: Partial<ModelMetadata>) => void }) {
  return <label>Meaning identifier (URI)<input maxLength={2048} value={value.semanticId || ""} placeholder="urn:example:press:motor-load" onChange={event => onChange({ semanticId: event.target.value || undefined })} /><small>Optional. A stable identifier for what the field means when sharing it with another system.</small></label>;
}
export function ModelUnitField({ value, onChange, compact = false }: { value: ModelMetadata; onChange: (patch: Partial<ModelMetadata>) => void; compact?: boolean }) {
  const id = useId(), [units, setUnits] = useState<{ code: string; name: string }[]>([]);
  useEffect(() => { const controller = new AbortController(); void api<{ items: typeof units }>("/model/units", "GET", undefined, controller.signal).then(result => setUnits(result.items)).catch(() => {}); return () => controller.abort(); }, []);
  return <div className={compact ? "model-field-unit" : "model-grid"}><label>Unit<input list={id} value={value.unit || ""} placeholder={value.unitSystem === "ucum" ? "Cel, %, kPa, /min" : "e.g. %, °C, parts"} onChange={event => onChange({ unit: event.target.value || undefined })} /><datalist id={id}>{units.map(unit => <option key={unit.code} value={unit.code}>{unit.name}</option>)}</datalist><small>Optional. Describes the value without converting it.{compact && value.unitSystem === "ucum" ? " Standard unit validation is on." : ""}</small></label>{!compact && <ModelUnitSystemField value={value} onChange={onChange} />}</div>;
}
export function ModelAlarmFields({ value = [], onChange }: { value?: ModelAlarm[]; onChange: (alarms: ModelAlarm[]) => void }) {
  const patch = (index: number, next: Partial<ModelAlarm>) => onChange(value.map((alarm, at) => at === index ? { ...alarm, ...next } : alarm));
  function add() { const ids = new Set(value.map(item => item.id)); let next = value.length + 1; while (ids.has(`alarm${next}`)) next++; onChange([...value, { id: `alarm${next}`, name: `Alarm ${next}`, enabled: true, mode: "high", setpoint: 90, deadband: 1, priority: 2 }]); }
  return <section className="model-contract-section"><p>Create an alarm when a value reaches a limit. These are separate from data quality checks. You can adjust the limits for each piece of equipment.</p>{value.map((alarm, index) => <fieldset className="model-card" key={index}><legend>{alarm.name || alarm.id}</legend><div className="model-grid"><label>Alarm ID<input value={alarm.id} onChange={event => patch(index, { id: event.target.value })} /></label><label>Name<input value={alarm.name} onChange={event => patch(index, { name: event.target.value })} /></label><label>Condition<select value={alarm.mode} onChange={event => patch(index, { mode: event.target.value as ModelAlarm["mode"] })}><option value="high">At or above threshold</option><option value="low">At or below threshold</option><option value="equal">Equals value</option></select></label><label>Threshold<input type="number" value={alarm.setpoint} onChange={event => patch(index, { setpoint: Number(event.target.value) })} /></label><label>Deadband<input type="number" min={0} value={alarm.deadband ?? 0} onChange={event => patch(index, { deadband: Number(event.target.value) })} /></label><label>Priority<select value={alarm.priority ?? 1} onChange={event => patch(index, { priority: Number(event.target.value) })}>{[1, 2, 3, 4].map(priority => <option key={priority} value={priority}>{priority}</option>)}</select></label></div><label>Message<input value={alarm.message || ""} onChange={event => patch(index, { message: event.target.value || undefined })} /></label><div className="model-actions"><label className="model-checkbox"><input type="checkbox" checked={alarm.enabled !== false} onChange={event => patch(index, { enabled: event.target.checked })} />Alarm enabled</label><button type="button" className="button small danger" onClick={() => onChange(value.filter((_item, at) => at !== index))}>Remove alarm</button></div></fieldset>)}<button type="button" className="button small" disabled={value.length >= 16} onClick={add}>Add alarm</button></section>;
}
export function ModelEnumField({ value = [], dataType, onChange }: { value?: ModelScalar[]; dataType?: string; onChange: (values: ModelScalar[] | undefined) => void }) {
  return <label>Allowed values (one per line)<textarea rows={4} value={value.map(String).join("\n")} placeholder={dataType === "String" ? "Stopped\nRunning\nFault" : "0\n1\n2"} onChange={event => onChange(event.target.value ? event.target.value.split("\n").map(item => modelScalar(item, dataType || "String")) : undefined)} /><small>Leave empty to accept any value of the field's data type. Values outside this list become data issues; the original value remains visible.</small></label>;
}
export function ModelContractFields({ value, onChange, includeSemantic = true }: { value: ModelMember; onChange: (patch: Partial<ModelMember>) => void; includeSemantic?: boolean }) {
  const numeric = !["String", "Boolean"].includes(value.dataType || "String"), enumeration = value.dataType === "String" || /Int/.test(value.dataType || "");
  return <><details className="model-contract-section"><summary>Quality rules</summary><p>Rules affect this modeled field only. Its original value and source quality remain available.</p>{numeric && <><label className="model-checkbox"><input type="checkbox" checked={Boolean(value.range)} onChange={event => onChange({ range: event.target.checked ? { low: 0, high: 100 } : undefined })} />Check an expected number range</label>{value.range && <div className="model-grid"><label>Minimum<input type="number" value={value.range.low} onChange={event => onChange({ range: { low: Number(event.target.value), high: value.range!.high } })} /></label><label>Maximum<input type="number" value={value.range.high} onChange={event => onChange({ range: { low: value.range!.low, high: Number(event.target.value) } })} /></label></div>}</>}<label>Mark data stale after (ms)<input type="number" min={0} max={86400000} value={value.freshnessMs || 0} onChange={event => onChange({ freshnessMs: Number(event.target.value) })} /><small>Use 0 to turn this check off. Every received sample counts, even when its value has not changed.</small></label>{enumeration && <ModelEnumField value={value.enumValues} dataType={value.dataType} onChange={enumValues => onChange({ enumValues })} />}</details>{numeric && <details className="model-contract-section"><summary>Process alarms ({value.alarms?.length || 0})</summary><ModelAlarmFields value={value.alarms} onChange={alarms => onChange({ alarms })} /></details>}{includeSemantic && <details className="model-contract-section"><summary>Advanced metadata</summary><ModelSemanticField value={value} onChange={onChange} /></details>}</>;
}
