import { useEffect, useMemo, useState } from "react";
import type { KeyboardEvent } from "react";
import { modelScalar, type ModelDefinition, type ModelInstance, type ModelPackage, type ModelParameter } from "./modelWorkspace";
import { pasteModelInstances, type ModelSourceTag } from "./modelBuilderOperations";
import { resolveModelInstances } from "./modelResolution";
import { modelParameterValueError } from "./modelParameterRules";
import type { ModelFolderSuggestion } from "./modelParameterize";
import { acceptsBuilderDrag } from "./modelBuilderLibrary";
import { BuilderDialog } from "./modelBuilderPanels";
import type { Tag } from "./types";
import { modelEquipmentReadiness, modelReadinessContext, type ModelReadiness } from "./modelReadiness";
import "./modelReadiness.css";
type Resolution = ReturnType<typeof resolveModelInstances>[number];
type Props = { model: ModelPackage; savedModel: ModelPackage; liveTags: Tag[]; definition: ModelDefinition; tags: ModelSourceTag[]; suggestions: ModelFolderSuggestion[]; onChange: (model: ModelPackage) => void; onEdit: (index: number) => void; onFolder: (folder: string) => void; onFindFolders: () => void; onSuggest: (suggestions: ModelFolderSuggestion[]) => void; onAnnounce: (message: string) => void; onResolution?: (messages: string[]) => void; onIssues?: (path: string) => void; onVerify?: (path: string) => void; selectedPath?: string; fromAskSpark?: string[] };
export default function ModelBuilderInstances(props: Props) {
  const [selected, setSelected] = useState(new Set<number>()), [page, setPage] = useState(0), [paste, setPaste] = useState(false), [over, setOver] = useState(false);
  const rows = useMemo(() => props.model.instances.map((instance, index) => ({ instance, index })).filter(row => row.instance.definitionId === props.definition.id), [props.model.instances, props.definition.id]);
  const resolutions = useModelResolutions(props.model, props.tags), pageCount = Math.max(1, Math.ceil(rows.length / 100)), currentPage = Math.min(page, pageCount - 1);
  const readinessContext = useMemo(() => modelReadinessContext(props.model, props.savedModel, props.liveTags), [props.model, props.savedModel, props.liveTags]);
  const readiness = useMemo(() => rows.map(row => modelEquipmentReadiness(row.instance, resolutions?.[row.index], readinessContext)), [rows, resolutions, readinessContext]);
  const ready = readiness.filter(value => value?.state === "ready").length;
  useEffect(() => { props.onResolution?.(rows.flatMap(row => { const result = resolutions?.[row.index]; return result && result.status !== "valid" ? [`${row.instance.path}: ${result.errors.join("; ") || `${result.total - result.resolved} unresolved members`}`] : []; }).slice(0, 20)); }, [props.onResolution, resolutions, rows]);
  function patch(index: number, instance: ModelInstance) { props.onChange({ ...props.model, instances: props.model.instances.map((item, at) => at === index ? instance : item) }); }
  function add() { if (props.model.instances.length >= 2000) { props.onAnnounce("The gateway supports at most 2,000 equipment items."); return; } const used = new Set(props.model.instances.map(item => item.path)); let suffix = 1; while (used.has(`[default]Models/${props.definition.id}/Unit${suffix}`)) suffix++; props.onChange({ ...props.model, instances: [...props.model.instances, { path: `[default]Models/${props.definition.id}/Unit${suffix}`, definitionId: props.definition.id, version: props.definition.version, enabled: true, parameters: {}, overrides: {} }] }); setPage(Math.floor(rows.length / 100)); props.onAnnounce("Equipment added to your draft. Fill in its values to connect the model fields."); }
  function upgrade() { props.onChange({ ...props.model, instances: props.model.instances.map((item, index) => selected.has(index) && item.definitionId === props.definition.id ? { ...item, version: props.definition.version } : item) }); props.onAnnounce(`Selected equipment now uses ${props.definition.id} v${props.definition.version}. Its values and custom settings are kept.`); }
  return <section className={`model-instance-workbench ${over ? "drop-active" : ""}`} aria-label="Equipment" onDragOver={event => { if (acceptsBuilderDrag(event, ["folder"])) { event.preventDefault(); setOver(true); } }} onDragLeave={() => setOver(false)} onDrop={event => { const folder = event.dataTransfer.getData("application/x-spark-tag-folder"); if (folder) { event.preventDefault(); setOver(false); props.onFolder(folder); } }}><header><h4>{props.definition.id} equipment <small>{rows.length}</small></h4><span className="model-resolution-summary">{resolutions ? `${ready} of ${rows.length} receiving good data` : "Checking links…"}</span></header>
    <p className="model-help">Each machine is an instance of this model: the same fields, connected to its own data.</p><div className="model-builder-toolbar"><button type="button" className="button small primary" onClick={add}>＋ Add equipment</button><details className="model-equipment-actions"><summary>Bulk actions</summary><div className="model-builder-toolbar"><button type="button" className="button small" onClick={() => setPaste(true)}>Paste spreadsheet rows</button><button type="button" className="button small" disabled={!rows.some(row => selected.has(row.index))} onClick={upgrade}>Update selected to v{props.definition.version}</button></div></details></div>
    {rows.length > 0 && <div className="model-instance-table"><table role="grid" aria-label={`${props.definition.id} equipment`} aria-rowcount={rows.length + 1} onKeyDown={gridKey}><thead><tr><th aria-label="Selection"><input type="checkbox" aria-label="Select all equipment using this model" checked={rows.length > 0 && rows.every(row => selected.has(row.index))} onChange={event => setSelected(event.target.checked ? new Set(rows.map(row => row.index)) : new Set())} /></th><th>Equipment name</th><th>On</th>{props.definition.parameters?.map(parameter => <th key={parameter.name}>{parameter.name}<small>{parameter.type}</small></th>)}<th>Status</th></tr></thead><tbody>{rows.slice(currentPage * 100, currentPage * 100 + 100).map(({ instance, index }, offset) => <InstanceRow key={index} instance={instance} index={currentPage * 100 + offset} selected={selected.has(index)} highlighted={props.selectedPath === instance.path} fromAskSpark={props.fromAskSpark?.includes(instance.path)} shell={props.definition} pinned={props.model.udtDefinitions.find(type => type.id === instance.definitionId && type.version === instance.version)} resolution={resolutions?.[index]} readiness={readiness[currentPage * 100 + offset]} onInspect={props.onVerify ? () => props.onVerify?.(instance.path) : undefined} onIssues={props.onIssues ? () => props.onIssues?.(instance.path) : undefined} onSelect={checked => setSelected(previous => { const next = new Set(previous); if (checked) next.add(index); else next.delete(index); return next; })} onChange={next => patch(index, next)} onEdit={() => props.onEdit(index)} />)}</tbody></table></div>}
    {!rows.length && <div className="model-equipment-empty"><strong>One model, many machines</strong><p>Add your first machine, such as Press01. For similar machines, use Find matching folders below.</p><small>You can set up equipment before saving the model.</small></div>}{pageCount > 1 && <div className="model-builder-toolbar"><button type="button" className="button small" disabled={currentPage === 0} onClick={() => setPage(currentPage - 1)}>Previous</button><small>{rows.length ? currentPage * 100 + 1 : 0}–{Math.min(rows.length, currentPage * 100 + 100)} of {rows.length}</small><button type="button" className="button small" disabled={currentPage + 1 >= pageCount} onClick={() => setPage(currentPage + 1)}>Next</button></div>}
    <BuilderSuggestions suggestions={props.suggestions} onAdd={props.onSuggest} onFind={props.onFindFolders} />
    {paste && <PasteInstances definition={props.definition} model={props.model} onClose={() => setPaste(false)} onApply={instances => { props.onChange({ ...props.model, instances: [...props.model.instances, ...instances] }); setPaste(false); props.onAnnounce(`Added ${instances.length} pieces of equipment from your spreadsheet.`); }} />}
  </section>;
}
function useModelResolutions(model: ModelPackage, tags: ModelSourceTag[]) {
  const immediate = useMemo(() => model.instances.length <= 200 ? resolveModelInstances(model.instances, model.udtDefinitions, tags, model.mappingProfiles) : undefined, [model.instances, model.udtDefinitions, model.mappingProfiles, tags]);
  const [deferred, setDeferred] = useState<{ model: ModelPackage; tags: ModelSourceTag[]; values: Resolution[] }>();
  useEffect(() => { if (model.instances.length <= 200) return; const timer = setTimeout(() => setDeferred({ model, tags, values: resolveModelInstances(model.instances, model.udtDefinitions, tags, model.mappingProfiles) }), 150); return () => clearTimeout(timer); }, [model, tags]);
  return immediate || (deferred?.model === model && deferred.tags === tags ? deferred.values : undefined);
}
function gridKey(event: KeyboardEvent<HTMLTableElement>) {
  if (!(event.target instanceof HTMLElement) || !["ArrowDown", "ArrowUp"].includes(event.key)) return;
  const row = event.target.closest("tr"), cell = event.target.closest("td,th"), rows = Array.from(event.currentTarget.querySelectorAll("tr"));
  if (!row || !cell) return;
  const column = Array.from(row.children).indexOf(cell), at = rows.indexOf(row), next = rows[at + (event.key === "ArrowDown" ? 1 : -1)];
  const target = next?.children[column]?.querySelector<HTMLElement>("input:not(:disabled),button,summary"); if (target) { event.preventDefault(); target.focus(); }
}
const equipmentName = (path: string) => path.slice(Math.max(path.lastIndexOf("/"), path.indexOf("]")) + 1);
function InstanceRow({ instance, index, shell, pinned, resolution, readiness, selected, highlighted, fromAskSpark, onSelect, onChange, onEdit, onIssues, onInspect }: { instance: ModelInstance; index: number; shell: ModelDefinition; pinned?: ModelDefinition; resolution?: Resolution; readiness?: ModelReadiness; selected: boolean; highlighted: boolean; fromAskSpark?: boolean; onSelect: (checked: boolean) => void; onChange: (instance: ModelInstance) => void; onEdit: () => void; onIssues?: () => void; onInspect?: () => void }) {
  return <tr aria-rowindex={index + 2} aria-selected={selected} className={highlighted ? "selected" : undefined} draggable onDragStart={event => { if (event.target instanceof HTMLInputElement) { event.preventDefault(); return; } event.dataTransfer.setData("application/x-spark-model-instance", instance.path); event.dataTransfer.effectAllowed = "move"; }}><td><input type="checkbox" checked={selected} aria-label={`Select ${instance.path}`} onChange={event => onSelect(event.target.checked)} /></td><td><input aria-label={`Equipment name ${index + 1}`} title={instance.path} value={equipmentName(instance.path)} onChange={event => onChange({ ...instance, path: instance.path.slice(0, instance.path.length - equipmentName(instance.path).length) + event.target.value })} /><button type="button" className="model-version-button" onClick={onEdit}>v{instance.version} · Details & settings</button>{fromAskSpark && <small className="model-badge">from Ask Spark</small>}</td><td><input type="checkbox" aria-label={`Enable ${instance.path}`} checked={instance.enabled !== false} onChange={event => onChange({ ...instance, enabled: event.target.checked })} /></td>{shell.parameters?.map(parameter => { const declaration = pinned?.parameters?.find(item => item.name === parameter.name); return <td key={parameter.name}><InstanceParameter parameter={declaration || parameter} supported={Boolean(declaration)} instance={instance} onChange={onChange} /></td>; })}<td><ResolutionCell value={resolution} readiness={readiness} onEdit={onEdit} onIssues={onIssues} onInspect={onInspect} /></td></tr>;
}
function InstanceParameter({ parameter, supported, instance, onChange }: { parameter: ModelParameter; supported: boolean; instance: ModelInstance; onChange: (instance: ModelInstance) => void }) {
  const value = instance.parameters?.[parameter.name], issue = value === undefined ? parameter.required && parameter.default === undefined ? "Enter a value" : undefined : modelParameterValueError(parameter.type, value);
  return <><input aria-label={`${instance.path} ${parameter.name}`} disabled={!supported} aria-invalid={Boolean(issue)} title={!supported ? "Update this equipment to the selected model version to edit this value" : issue || parameter.type} value={value === undefined ? "" : String(value)} placeholder={parameter.default === undefined ? parameter.required ? "Required" : "Optional" : String(parameter.default)} onChange={event => { const parameters = { ...instance.parameters }; if (event.target.value === "") delete parameters[parameter.name]; else parameters[parameter.name] = modelScalar(event.target.value, parameter.type); onChange({ ...instance, parameters }); }} />{issue && <small className="model-warning">{issue}</small>}</>;
}
function ResolutionCell({ value, readiness, onEdit, onIssues, onInspect }: { value?: Resolution; readiness?: ModelReadiness; onEdit: () => void; onIssues?: () => void; onInspect?: () => void }) {
  if (!value || !readiness) return <span className="muted">Checking…</span>;
  if (readiness.state === "ready") return <span className="model-readiness ready" title={readiness.message}>✓ Ready</span>;
  return <details className="model-row-resolution"><summary className={`model-readiness ${readiness.state}`}>{readiness.label}</summary><p>{readiness.message}</p>{value.status !== "valid" && <ul>{value.errors.map((error, index) => <li key={index}>{error}</li>)}{value.members.filter(member => member.status !== "valid").map(member => <li key={member.path}><strong>{member.path}</strong><span>{member.target}</span>{member.message}</li>)}</ul>}{readiness.fields.length > 0 && <><small>{readiness.good} of {readiness.total} fields receiving good data</small><ul>{readiness.fields.slice(0, 8).map(field => <li key={field.path}><strong>{field.path}</strong><span>{field.label}</span></li>)}</ul>{readiness.fields.length > 8 && <small>{readiness.fields.length - 8} more fields need attention.</small>}</>}<div className="model-readiness-actions">{readiness.state === "issue" && onIssues && <button type="button" className="button small" onClick={onIssues}>Review data issues</button>}{readiness.state !== "setup" && onInspect && <button type="button" className="button small" onClick={onInspect}>Inspect live values</button>}<button type="button" className="button small" onClick={onEdit}>Edit this equipment</button></div></details>;
}
function BuilderSuggestions({ suggestions, onAdd, onFind }: { suggestions: ModelFolderSuggestion[]; onAdd: (items: ModelFolderSuggestion[]) => void; onFind: () => void }) {
  return <section className="model-suggestions"><header><h4>Similar equipment</h4><button type="button" className="button small" onClick={onFind}>Find matching folders</button></header>{suggestions.map(item => <div key={item.folder}><span title={item.folder}>{item.value}<small>{item.matched} of {item.total} fields match</small></span><button type="button" className="button small" aria-label={`Add ${item.value} equipment`} onClick={() => onAdd([item])}>＋</button></div>)}{suggestions.some(item => item.complete) && <button type="button" className="button small" onClick={() => onAdd(suggestions.filter(item => item.complete))}>Add all matches</button>}</section>;
}
function PasteInstances({ definition, model, onClose, onApply }: { definition: ModelDefinition; model: ModelPackage; onClose: () => void; onApply: (rows: ModelInstance[]) => void }) {
  const [text, setText] = useState(""), [error, setError] = useState("");
  return <BuilderDialog title="Add equipment from a spreadsheet" onClose={onClose}><p>Paste a header row: <code>path{definition.parameters?.map(parameter => `,${parameter.name}`).join("")}</code>. Tabs or commas are accepted, up to 2,000 total pieces of equipment. Each row creates one machine. Empty parameter cells use their default values.</p><label>Spreadsheet rows<textarea autoFocus rows={12} value={text} onChange={event => setText(event.target.value)} /></label>{error && <p role="alert" className="security-error">{error}</p>}<footer><button type="button" className="button primary" disabled={!text.trim()} onClick={() => { try { onApply(pasteModelInstances(text, definition, model.instances)); } catch (reason) { setError(reason instanceof Error ? reason.message : String(reason)); } }}>Add equipment to draft</button></footer></BuilderDialog>;
}
