import { useState } from "react";
import type { DragEvent } from "react";
import { ModelMetadataFields } from "./modelWorkspaceFields";
import { definitionKey, type ModelDefinition, type ModelMember } from "./modelWorkspace";
import { acceptsBuilderDrag, readBuilderDrag, writeBuilderDrag, type BuilderDrag } from "./modelBuilderLibrary";
export const memberIcon = (kind: ModelMember["kind"]) => ({ reference: "⇢", memory: "▣", expression: "ƒ", type: "◆", opcua: "⌁", device: "⌁" })[kind];
export function memberRules(member: ModelMember): string {
  const rules = [member.range ? `${member.range.low}–${member.range.high}` : "", member.freshnessMs ? `stale ${member.freshnessMs / 1000} s` : "", member.enumValues?.length ? `${member.enumValues.length} values` : "", member.alarms?.length ? `${member.alarms.length} alarm${member.alarms.length === 1 ? "" : "s"}` : ""];
  return rules.filter(Boolean).join(" · ");
}
export const memberSummary = (member: ModelMember) => member.kind === "type" ? `${member.definitionId || "Choose type"} v${member.version || 1}` : member.kind === "reference" ? member.target : member.kind === "expression" ? member.expression : member.kind === "memory" ? String(member.value ?? "") : `${member.connectionId || "?"} / ${member.nodeId || "?"}`;
type Props = { value?: ModelDefinition; hasModels?: boolean; onUseStarter?: () => void; saved: boolean; fromAskSpark?: boolean; selectedMember?: number; highlightedParameter?: string; onChange: (next: ModelDefinition) => void; onEditVersion: () => void; onMember: (index: number) => void; onParameter: (index: number) => void; onAddParameter: () => void; onAddMember: (kind: ModelMember["kind"]) => void; onDrop: (drag: BuilderDrag, at?: number, replace?: boolean) => void; onParameterize: () => void; onRemoveType: () => void; onNew: () => void; onAnnounce: (message: string) => void };
export default function ModelBuilderShell(props: Props) {
  const [over, setOver] = useState(false), type = props.value;
  const dragOver = (event: DragEvent) => { if (!props.saved && acceptsBuilderDrag(event, type ? undefined : ["tag", "folder"])) { event.preventDefault(); event.stopPropagation(); setOver(true); } else event.dataTransfer.dropEffect = "none"; };
  const dragLeave = (event: DragEvent) => { if (!event.currentTarget.contains(event.relatedTarget as Node)) setOver(false); };
  const drop = (event: DragEvent) => { event.preventDefault(); event.stopPropagation(); setOver(false); const drag = readBuilderDrag(event); if (drag && !props.saved) props.onDrop(drag); };
  if (!type) return <section className={`model-shell-empty ${over ? "drop-active" : ""}`} onDragOver={dragOver} onDragLeave={dragLeave} onDrop={drop}><div className="model-example-card" aria-hidden="true"><span>One blueprint. Many machines.</span><strong>Press</strong><div><span>Speed</span><small>Number · rpm</small></div><div><span>Running</span><small>On / off</small></div><div><span>Part count</span><small>Whole number</small></div></div><h3>{props.hasModels ? "Choose a model to work on" : "How would you like to start?"}</h3><p>{props.hasModels ? "Choose a model in the Models list to see its fields and machines, or start another one." : "A model groups useful values, like Speed and Running. Build it once, then use it for every machine."}</p><div className="model-start-choices">{props.onUseStarter && <button type="button" className="button primary" onClick={props.onUseStarter}><strong>Use a starter</strong><small>Explore Motor, Pump, Press or OEE with example values.</small></button>}<button type="button" className={props.onUseStarter ? "button" : "button primary"} onClick={props.onNew}><strong>Use my data</strong><small>Choose your own tags or begin with manual values.</small></button></div><small>Drag a tag folder here any time to create a model from your data.</small></section>;
  return <section className="model-type-shell" onDragOver={dragOver} onDragLeave={dragLeave} onDrop={drop} aria-label={`Model ${definitionKey(type)}`}><header><div>{props.saved ? <strong>{type.id}</strong> : <label className="model-type-id">Model name<input value={type.id} placeholder="e.g. Press" onChange={event => props.onChange({ ...type, id: event.target.value })} /></label>}<span className="model-badge">v{type.version} · {props.saved ? "saved" : "draft"}</span>{props.fromAskSpark && <span className="model-badge">from Ask Spark</span>}</div><div className="model-builder-toolbar">{props.saved && <button type="button" className="button" onClick={props.onEditVersion}>Edit a new version</button>}<details className="model-shell-menu"><summary aria-label="Model actions">⋯</summary><button type="button" className="button small" disabled={props.saved} onClick={props.onParameterize}>Reuse with other machines…</button><button type="button" className="button small danger" onClick={props.onRemoveType}>Remove model version</button></details></div></header>
    {props.saved && <p className="model-readonly-note">This version is saved. Edit a new version to make changes; existing equipment keeps using this one.</p>}
    <fieldset disabled={props.saved} className="model-shell-metadata"><ModelMetadataFields value={type} onChange={patch => props.onChange({ ...type, ...patch })} /></fieldset>
    <div className="model-fields-heading"><h4>Fields</h4><span>{type.members.length} / 128</span></div><div className={`model-member-list ${over ? "drop-active" : ""}`} aria-label="Model fields" onDragOver={dragOver} onDragLeave={dragLeave} onDrop={drop}>
      {type.members.map((member, index) => <MemberRow key={index} member={member} index={index} count={type.members.length} selected={props.selectedMember === index} highlighted={Boolean(props.highlightedParameter && JSON.stringify(member).includes(`{${props.highlightedParameter}}`))} saved={props.saved} onSelect={() => props.onMember(index)} onDrop={props.onDrop} onAnnounce={props.onAnnounce} />)}
      {!type.members.length && <div className="model-drop-empty"><strong>Drop your first tags here</strong><p>Drag a tag or a whole folder from the data library. Each tag becomes a field in this model.</p><small>You can also select a tag and choose “Add to model”.</small></div>}<small className="model-member-count">Click a field to edit it. Drag to reorder, or use Alt+↑ / ↓.</small>
    </div><div className="model-builder-toolbar"><button type="button" className="button small" disabled={props.saved || type.members.length >= 128} onClick={() => props.onAddMember("memory")}>＋ Manual value</button><button type="button" className="button small" disabled={props.saved || type.members.length >= 128} onClick={() => props.onAddMember("expression")}>＋ Calculation</button></div>
    <section className="model-reuse-section"><header><h4>Asks each machine for</h4><small>Optional</small></header><p className="model-help">Fill-in values let one model use each machine’s own data, like its device name or source folder.</p><div className="model-parameter-chips" aria-label="Model parameters">{type.parameters?.map((parameter, index) => <button type="button" key={index} className={`model-parameter-chip ${props.highlightedParameter === parameter.name ? "active" : ""}`} onClick={() => props.onParameter(index)}>{`{${parameter.name}}`}<small>{parameter.type}</small></button>)}<button type="button" className="button small" disabled={props.saved || (type.parameters?.length || 0) >= 32} onClick={props.onAddParameter}>＋ Add parameter</button></div></section>
    <details className="model-advanced"><summary>Advanced: connect a field directly</summary><p className="model-help">Read directly from a connection instead of using an existing tag.</p><div className="model-builder-toolbar">{(["opcua", "device"] as const).map(kind => <button type="button" key={kind} className="button small" disabled={props.saved || type.members.length >= 128} onClick={() => props.onAddMember(kind)}>＋ {kind === "opcua" ? "OPC UA field" : "Device field"}</button>)}</div></details>
  </section>;
}
function MemberRow({ member, index, count, selected, highlighted, saved, onSelect, onDrop, onAnnounce }: { member: ModelMember; index: number; count: number; selected: boolean; highlighted: boolean; saved: boolean; onSelect: () => void; onDrop: Props["onDrop"]; onAnnounce: (message: string) => void }) {
  const [over, setOver] = useState(false);
  return <div className={`model-member-row ${selected ? "selected" : ""} ${highlighted ? "parameter-highlight" : ""} ${over ? "drop-active" : ""}`} draggable={!saved} onDragStart={event => writeBuilderDrag(event, { kind: "member", path: String(index) })} onDragOver={event => { if (saved || !acceptsBuilderDrag(event)) return; event.preventDefault(); event.stopPropagation(); setOver(true); }} onDragLeave={() => setOver(false)} onDrop={event => { event.preventDefault(); event.stopPropagation(); setOver(false); const drag = readBuilderDrag(event); if (drag && !saved) onDrop(drag, index, member.kind === "reference" && drag.kind === "tag"); }}>
    <button type="button" className="model-member-main" onClick={onSelect} onKeyDown={event => { if (saved || !event.altKey || !["ArrowUp", "ArrowDown"].includes(event.key)) return; event.preventDefault(); const next = index + (event.key === "ArrowUp" ? -1 : 1); if (next < 0 || next >= count) { onAnnounce("This member is already at the edge of the list."); return; } onDrop({ kind: "member", path: String(index) }, next); }}><span className="model-drag-grip" aria-hidden="true">⠿</span><span aria-label={member.kind}>{memberIcon(member.kind)}</span><strong>{member.path || "Unnamed member"}</strong><small>{member.dataType || member.definitionId}{member.unit && ` · ${member.unit}`}</small><span className="model-member-source" title={memberSummary(member)}>{memberSummary(member)}</span>{memberRules(member) && <span className="model-member-rules" title="Data rules">{memberRules(member)}</span>}</button>
  </div>;
}
