import { useEffect, useState } from "react";
import type { ReactNode } from "react";
import type { ModelPackage } from "./modelWorkspace";
import { modelErrorText } from "./modelOperationsApi";
import { deleteModelPublisher, discardModelPublisherQueue, getModelPublishing, newModelPublisher, previewModelPublishing, saveModelPublisher, testModelPublisher, type ModelPublisher, type ModelPublisherDiagnostic, type ModelPublishing, type ModelPublishPreview } from "./modelPublisherApi";

type PublisherFields = { value: ModelPublisher; patch: (patch: Partial<ModelPublisher>) => void };
const equipmentName = (path: string) => path.split("/").at(-1)?.replace(/^\[[^\]]+\]/, "") || path;
function PublisherStep({ number, title, children }: { number: number; title: string; children: ReactNode }) {
  return <section className="model-publisher-step"><h3><span aria-hidden="true">{number}</span>{title}</h3><div>{children}</div></section>;
}
function PublisherDeliveryFields({ value, patch }: PublisherFields) {
  return <details className="model-contract-section model-publisher-delivery"><summary>Delivery options</summary><p>Defaults send one object when values or quality change. Open these settings to change the topic, message shape or delivery behavior.</p><div className="model-grid"><label>Topic prefix<input value={value.topicPrefix} onChange={event => patch({ topicPrefix: event.target.value })} /></label><label>Message format<select value={value.shape} onChange={event => patch({ shape: event.target.value as ModelPublisher["shape"] })}><option value="object">One object per equipment</option><option value="leaves">One message per field</option></select></label><label>Publish when<select value={value.mode} onChange={event => patch({ mode: event.target.value as ModelPublisher["mode"] })}><option value="onChange">Values or quality change</option><option value="interval">At a fixed interval</option></select></label><label>Check interval (ms)<input type="number" min={250} max={86400000} value={value.intervalMs} onChange={event => patch({ intervalMs: Number(event.target.value) })} /><small>How often to check for changes or send a scheduled message.</small></label><label>Delivery guarantee<select value={value.qos} onChange={event => patch({ qos: Number(event.target.value) as 0 | 1 })}><option value={0}>Best effort · QoS 0</option><option value={1}>Wait for broker acknowledgment · QoS 1</option></select><small>QoS 1 retries unacknowledged messages; a receiver may see duplicates.</small></label><label className="model-checkbox"><input type="checkbox" checked={value.retain} onChange={event => patch({ retain: event.target.checked })} />Keep latest message on the broker</label></div><h4>Queue while disconnected</h4><p>Messages wait on disk. When the queue is full, new batches are rejected and counted below; queued messages stay intact.</p><div className="model-grid"><label>Maximum queued messages<input type="number" min={1} max={10000} value={value.queueLimit} onChange={event => patch({ queueLimit: Number(event.target.value) })} /></label><label>Maximum queue size (bytes)<input type="number" min={1024} max={67108864} value={value.queueBytes} onChange={event => patch({ queueBytes: Number(event.target.value) })} /></label></div></details>;
}
function PublisherDiagnostics({ value }: { value?: ModelPublisherDiagnostic }) {
  return <section className="model-card model-publisher-diagnostics" aria-label="Delivery status"><h3>Delivery status{value ? ` · ${value.state}` : ""}</h3>{!value && <p>No delivery activity yet. Save a publisher to see its queue, deliveries and errors here.</p>}{value?.lastError && <p role="alert" className="security-error">{value.lastError}</p>}<dl className="model-facts"><dt>Queued</dt><dd>{value?.queuedCount ?? 0} messages · {(value?.queuedBytes ?? 0).toLocaleString()} bytes</dd><dt>Delivered</dt><dd>{value?.delivered ?? 0}</dd><dt>Retries</dt><dd>{value?.retries ?? 0}</dd><dt>Rejected</dt><dd>{value?.rejected ?? 0}</dd><dt>Last delivered</dt><dd>{value?.lastDeliveredAt ? new Date(value.lastDeliveredAt).toLocaleString() : "None"}</dd></dl>{value?.delivery && <p>{value.delivery}</p>}</section>;
}
function PublisherCredentials({ value, patch }: PublisherFields) {
  return <><div className="model-grid"><label>Name<input value={value.name} onChange={event => patch({ name: event.target.value })} /></label><label>Broker endpoint<input value={value.endpoint} onChange={event => patch({ endpoint: event.target.value })} placeholder="mqtts://broker.example.com:8883" /><small>Use mqtts for TLS. The gateway checks the broker's certificate.</small></label></div><details className="model-contract-section"><summary>Broker login (optional){value.username || value.hasPassword ? " · configured" : ""}</summary><div className="model-grid"><label>Username<input autoComplete="off" value={value.username || ""} onChange={event => patch({ username: event.target.value })} /></label><label>Password<input type="password" autoComplete="new-password" value={value.password || ""} placeholder={value.hasPassword ? "Saved securely; leave blank to keep" : "Optional"} onChange={event => patch({ password: event.target.value || undefined })} /></label></div>{value.hasPassword && <label className="model-checkbox"><input type="checkbox" checked={value.clearPassword === true} onChange={event => patch({ clearPassword: event.target.checked })} />Remove saved broker password</label>}</details></>;
}
function PublisherEquipment({ model, value, patch }: PublisherFields & { model: ModelPackage }) {
  const [filter, setFilter] = useState("");
  const matches = model.instances.filter(item => item.path.toLowerCase().includes(filter.toLowerCase()));
  return <><p>{value.instancePaths.length} selected. Only equipment saved on this gateway can be published.</p><label>Find saved equipment<input value={filter} onChange={event => setFilter(event.target.value)} /></label><div className="model-operation-list model-publisher-equipment">{matches.map(item => <label className="model-checkbox" key={item.path}><input type="checkbox" checked={value.instancePaths.includes(item.path)} onChange={event => patch({ instancePaths: event.target.checked ? [...value.instancePaths, item.path] : value.instancePaths.filter(path => path !== item.path) })} /><span><strong>{equipmentName(item.path)}</strong><small>{item.path}</small></span></label>)}</div>{!matches.length && <p>{model.instances.length ? "No equipment matches this search." : "Save equipment in Build models before creating a publisher."}</p>}</>;
}
function PublisherPreview({ value }: { value?: ModelPublishPreview }) {
  if (!value) return null;
  return <section className="model-card"><h4>{value.total} messages{value.truncated ? ` · showing first ${value.messages.length}` : ""}</h4><div className="model-operation-list">{value.messages.map((message, index) => <details key={index}><summary>{message.topic} · {message.bytes} bytes</summary><pre className="model-json-preview">{JSON.stringify(message.payload, null, 2)}</pre></details>)}</div></section>;
}
function PublisherConfirmation({ confirm, name, count, onCancel, onConfirm }: { confirm: "delete" | "queue"; name: string; count: number; onCancel: () => void; onConfirm: () => void }) { return <section className="model-card" role="alert"><h3>{confirm === "queue" ? `Discard ${count} queued messages?` : `Delete ${name}?`}</h3><p>{confirm === "queue" ? "These pending messages will not be delivered. This cannot be undone." : "The publisher will stop and its configuration will be removed."}</p><div className="model-actions"><button type="button" className="button" onClick={onCancel}>Cancel</button><button type="button" className="button danger" onClick={onConfirm}>{confirm === "queue" ? "Discard messages" : "Delete publisher"}</button></div></section>; }
function PublisherPicker({ data, draft, saved, dirty, onChoose }: { data?: ModelPublishing; draft?: ModelPublisher; saved?: ModelPublisher; dirty: boolean; onChoose: (value?: ModelPublisher) => void }) {
  return <div className="model-actions"><label>Publisher<select value={saved?.id || ""} disabled={Boolean(draft && dirty)} onChange={event => onChoose(data?.publishers.find(item => item.id === event.target.value))}><option value="">Choose publisher…</option>{data?.publishers.map(item => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><button type="button" className="button" disabled={!data || Boolean(draft && dirty)} onClick={() => onChoose(newModelPublisher())}>New publisher</button>{draft && dirty && <button type="button" className="button" onClick={() => onChoose(saved)}>Discard publisher edits</button>}</div>;
}
function PublisherTestStep({ value, dirty, loaded, onTest }: { value: ModelPublisher; dirty: boolean; loaded: boolean; onTest: () => void }) {
  return <PublisherStep number={4} title="Test the connection"><p>{dirty && !value.enabled ? "Save this configuration with delivery off and check the broker in one step." : "Check that the gateway can connect. The test itself sends no model messages."}</p><button type="button" className="button" disabled={!loaded || !value.instancePaths.length || (dirty && value.enabled)} onClick={onTest}>{dirty ? "Save and test broker" : "Test saved broker"}</button>{dirty && value.enabled && <small>Save changes below before testing, or turn delivery off to save and test together.</small>}</PublisherStep>;
}
export function ModelPublishingPanel({ model, onLockChange }: { model: ModelPackage; onLockChange: (locked: boolean) => void }) {
  const [data, setData] = useState<ModelPublishing>(), [draft, setDraft] = useState<ModelPublisher>(), [preview, setPreview] = useState<ModelPublishPreview>(), [error, setError] = useState(""), [notice, setNotice] = useState(""), [busy, setBusy] = useState(false), [confirm, setConfirm] = useState<"delete" | "queue" | null>(null);
  useEffect(() => { let active = true; void getModelPublishing().then(value => { if (active) setData(value); }).catch(reason => { if (active) setError(modelErrorText(reason)); }); return () => { active = false; }; }, []);
  const saved = data?.publishers.find(item => item.id === draft?.id), diagnostic = data?.diagnostics.find(item => item.id === draft?.id), dirty = JSON.stringify(draft) !== JSON.stringify(saved), queued = diagnostic?.queuedCount || 0;
  useEffect(() => { onLockChange(busy || Boolean(draft && dirty)); return () => onLockChange(false); }, [busy, draft, dirty, onLockChange]);
  async function perform(action: () => Promise<void>) { if (busy) return; setBusy(true); setError(""); setNotice(""); try { await action(); } catch (reason) { setError(modelErrorText(reason)); } finally { setBusy(false); } }
  function choose(next?: ModelPublisher) { setDraft(next); setPreview(undefined); setNotice(""); setError(""); setConfirm(null); }
  function patch(next: Partial<ModelPublisher>) { if (!draft) return; setDraft({ ...draft, ...next }); setPreview(undefined); setNotice(""); }
  async function refresh() { setData(await getModelPublishing()); }
  async function save() { if (!draft || !data) return; await saveModelPublisher(data.revision, draft); const next = await getModelPublishing(); setData(next); setDraft(next.publishers.find(item => item.id === draft.id)); setNotice(draft.enabled ? "Publisher saved. Delivery is enabled." : "Publisher saved with delivery off. You can test the broker before enabling it."); }
  async function test() { if (!draft) return; if (dirty) { if (draft.enabled) return; await save(); } const result = await testModelPublisher(draft.id); setNotice(result.message || (result.success ? "Broker connection succeeded. The test sends no messages." : "Broker connection failed.")); await refresh(); }
  async function remove() { if (!draft || !data) return; await deleteModelPublisher(data.revision, draft.id); choose(); await refresh(); setNotice("Publisher removed."); }
  async function discard() { if (!draft) return; const result = await discardModelPublisherQueue(draft.id); setConfirm(null); await refresh(); setNotice(`Discarded ${result.discarded} queued messages.`); }
  return <section className="model-operation-panel"><header><div><h2>Publish models to MQTT</h2><p>Choose equipment, preview its messages, then connect and enable delivery. Publisher settings save separately from your model draft.</p></div><button type="button" className="button" disabled={busy} onClick={() => void perform(refresh)}>Refresh delivery</button></header><fieldset disabled={busy} className="model-drawer-fields"><PublisherPicker data={data} draft={draft} saved={saved} dirty={dirty} onChoose={choose} />{error && <p role="alert" className="security-error">{error}</p>}{notice && <p role="status">{notice}</p>}{draft && <>
    <PublisherStep number={1} title="Choose equipment"><PublisherEquipment model={model} value={draft} patch={patch} /></PublisherStep>
    <PublisherStep number={2} title="Connect to a broker"><PublisherCredentials value={draft} patch={patch} /></PublisherStep>
    <PublisherStep number={3} title="Preview the messages"><p>Preview uses the latest saved model values and sends nothing to the broker.</p><PublisherDeliveryFields value={draft} patch={patch} /><button type="button" className="button" disabled={!draft.instancePaths.length} onClick={() => void perform(async () => setPreview(await previewModelPublishing(draft)))}>Preview topics and payloads</button><PublisherPreview value={preview} /></PublisherStep>
    <PublisherTestStep value={draft} dirty={dirty} loaded={Boolean(data)} onTest={() => void perform(test)} />
    <PublisherStep number={5} title="Enable delivery"><label className="model-checkbox"><input type="checkbox" checked={draft.enabled} onChange={event => patch({ enabled: event.target.checked })} />Enable publishing when saved</label><p>{draft.enabled ? "Saving will start delivery using these settings." : "Delivery stays off until you enable it and save."}</p><div className="model-actions"><button type="button" className="button primary" disabled={!data || !dirty || !draft.instancePaths.length} onClick={() => void perform(save)}>Save publisher</button></div></PublisherStep>
    {saved && <div className="model-actions"><button type="button" className="button danger" disabled={queued > 0} onClick={() => setConfirm("delete")}>Delete publisher</button>{queued > 0 && <button type="button" className="button danger" onClick={() => setConfirm("queue")}>Discard queued messages…</button>}</div>}{confirm && <PublisherConfirmation confirm={confirm} name={draft.name} count={queued} onCancel={() => setConfirm(null)} onConfirm={() => void perform(confirm === "queue" ? discard : remove)} />}</>}</fieldset><PublisherDiagnostics value={diagnostic} /></section>;
}
