import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import type { Connection, Tag } from "./types";
import { definitionKey, nextModelDefinition, type ModelDefinition, type ModelExpandedTag, type ModelInstance, type ModelMember, type ModelPackage } from "./modelWorkspace";
import { ModelOverrides } from "./modelWorkspaceInstances";
import { ModelParameterValues } from "./modelWorkspaceFields";
import { addNestedModelType, folderDropCandidates, referenceMembersFromTags, reorderModelMember, replaceModelReferenceTarget, validateModelNesting, type ModelSourceTag } from "./modelBuilderOperations";
import { applyModelParameterization, inferModelParameterization, modelInstanceFromFolder, offerModelParameterization, suggestedModelInstance, suggestModelFolders, type ModelParameterizationOffer } from "./modelParameterize";
import ModelBuilderLibrary, { type BuilderDrag } from "./modelBuilderLibrary";
import ModelBuilderShell from "./modelBuilderShell";
import ModelBuilderToolbar from "./modelBuilderToolbar";
import ModelBuilderInstances from "./modelBuilderInstances";
import { BuilderMemberEditor, BuilderParameterEditor } from "./modelBuilderDrawer";
import { BuilderDialog, BuilderDrawer, ModelBuilderPanels } from "./modelBuilderPanels";
import { resolveModelInstances } from "./modelResolution";
import "./modelBuilder.css";

export interface ModelBuilderProps { disabled?: boolean; model: ModelPackage; savedModel: ModelPackage; definitions: ModelExpandedTag[]; tags: Tag[]; connections: Connection[]; selectedType: string; onSelectType: (key: string) => void; onChange: (next: ModelPackage) => void; fromAskSpark?: string[]; onAnnounce?: (message: string) => void; onUseStarter?: () => void; onReview?: () => void; onVerify?: (path?: string) => void; onIssues?: (path: string) => void; hasChanges?: boolean; focusTarget?: string; libraryRequest?: number; onContextChange?: (context: { selection: string[]; resolution: string[] }) => void }
type Selection = { kind: "member" | "parameter" | "instance"; index: number };
type Offer = { typeKey: string; value: ModelParameterizationOffer };
type Confirmation = { title: string; description: string; model: ModelPackage; apply: () => void };
export default function ModelBuilder(props: ModelBuilderProps) {
  const { model, selectedType, onSelectType, onChange } = props;
  const surface = useRef<HTMLDivElement>(null), [libraryOpen, setLibraryOpen] = useState(readLibraryOpen);
  const [selection, setSelection] = useState<Selection>(), [message, setMessage] = useState(""), [offer, setOffer] = useState<Offer>(), [suggestionOffer, setSuggestionOffer] = useState<Offer>(), [confirm, setConfirm] = useState<Confirmation>(), [folder, setFolder] = useState<{ path: string; at?: number }>();
  const [resolution, setResolution] = useState<string[]>([]);
  const [selectedFolder, setSelectedFolder] = useState(""), [findFolder, setFindFolder] = useState(false);
  const definition = model.udtDefinitions.find(item => definitionKey(item) === selectedType), saved = props.savedModel.udtDefinitions.some(item => definitionKey(item) === selectedType);
  const sourceTags = useMemo(() => { const live = new Map(props.tags.map(tag => [tag.path, tag])); return props.definitions.map(tag => ({ ...tag, liveDataType: live.get(tag.path)?.dataType })); }, [props.definitions, props.tags]);
  const announce = useCallback((text: string) => { setMessage(text); props.onAnnounce?.(text); }, [props.onAnnounce]);
  const handleResolution = useCallback((messages: string[]) => setResolution(previous => JSON.stringify(previous) === JSON.stringify(messages) ? previous : messages), []);
  const activeOffer = suggestionOffer?.typeKey === selectedType ? suggestionOffer.value : undefined;
  const suggestions = useMemo(() => definition && activeOffer ? suggestModelFolders(definition, sourceTags, activeOffer).filter(suggestion => !model.instances.some(instance => instance.definitionId === definition.id && instance.parameters?.[activeOffer.parameterName] === suggestion.value)) : [], [definition, activeOffer, sourceTags, model.instances]);
  const usedTargets = useMemo(() => usedModelTargets(definition, model, sourceTags), [definition, model, sourceTags]);
  const pickType = (key: string) => { setSelection(undefined); setOffer(undefined); setFolder(undefined); setMessage(""); onSelectType(key); };
  const attempt = (action: () => void) => { try { action(); } catch (reason) { announce(reason instanceof Error ? reason.message : String(reason)); } };
  function showLibrary(open: boolean) { setLibraryOpen(open); try { localStorage.setItem(libraryKey, String(open)); } catch { /* The library still opens without browser storage. */ } }
  function showMachines() { requestAnimationFrame(() => surface.current?.querySelector(".model-instances-pane")?.scrollIntoView({ behavior: "smooth", block: "start" })); }
  useEffect(() => { if (props.libraryRequest) setLibraryOpen(true); }, [props.libraryRequest]);
  function changeType(next: ModelDefinition) {
    if (!definition || saved) throw new Error("Edit a new version before changing a saved model.");
    const key = definitionKey(next); if (key !== selectedType && model.udtDefinitions.some(item => definitionKey(item) === key)) throw new Error(`A model named ${key} already exists.`);
    const types = model.udtDefinitions.map(item => definitionKey(item) === selectedType ? next : renameNestedPin(item, selectedType, next));
    validateModelNesting(next, types);
    onChange({ ...model, udtDefinitions: types, instances: model.instances.map(item => definitionKey(itemIdentity(item)) === selectedType ? { ...item, definitionId: next.id, version: next.version } : item) });
    if (key !== selectedType) onSelectType(key);
  }
  function newType() { showLibrary(true); const next = emptyBuilderModel(model); onChange({ ...model, udtDefinitions: [...model.udtDefinitions, next] }); pickType(definitionKey(next)); announce("Your model is ready. Give it a name, then add tags from the data library."); }
  function startFromData(drag: BuilderDrag) {
    if (drag.kind !== "tag" && drag.kind !== "folder") throw new Error("Choose a model from the library, or drop source tags to create one.");
    const tags = drag.kind === "folder" ? folderDropCandidates(drag.path, sourceTags, []).tags : sourceTags.filter(tag => tag.path === drag.path);
    if (!tags.length) throw new Error("This selection contains no saved source tags.");
    const next = emptyBuilderModel(model), needsSelection = tags.length > 128, sourceFolder = drag.kind === "folder" ? drag.path : undefined;
    const result = referenceMembersFromTags(needsSelection ? [] : tags, [], sourceFolder); next.members = result.members;
    onChange({ ...model, udtDefinitions: [...model.udtDefinitions, next] }); pickType(definitionKey(next));
    if (needsSelection) setFolder({ path: drag.path });
    else { const suggested = offerModelParameterization(next, sourceTags, sourceFolder); if (suggested) setOffer({ typeKey: definitionKey(next), value: suggested }); }
    announce(`Created ${next.id} from your data. ${needsSelection ? "Choose the fields to include." : `Added ${next.members.length} linked fields.`}${result.warnings.length ? " " + result.warnings.join(" ") : ""}`);
  }
  function editVersion() { const next = nextModelDefinition(model, selectedType); onChange({ ...model, udtDefinitions: [...model.udtDefinitions, next] }); pickType(definitionKey(next)); announce(`Created ${next.id} v${next.version} as a draft. Existing equipment keeps using its saved version.`); }
  function addReferences(tags: ModelSourceTag[], sourceFolder?: string, at?: number) { if (!definition) throw new Error("Create or select a draft model first."); const result = referenceMembersFromTags(tags, definition.members, sourceFolder), members = [...definition.members]; members.splice(at ?? members.length, 0, ...result.members); const next = { ...definition, members }; changeType(next); const suggested = offerModelParameterization(next, sourceTags, sourceFolder); if (suggested) setOffer({ typeKey: selectedType, value: suggested }); announce(`Added ${result.members.length} linked field${result.members.length === 1 ? "" : "s"}.${result.warnings.length ? " " + result.warnings.join(" ") : ""}`); }
  function drop(drag: BuilderDrag, at?: number, replace = false) { if (props.disabled) return; attempt(() => {
    if (!definition) { startFromData(drag); return; }
    if (saved) throw new Error("Select an editable draft model, or choose Edit a new version.");
    if (drag.kind === "member") { const from = Number(drag.path); changeType(reorderModelMember(definition, from, at ?? definition.members.length - 1)); announce(`Reordered ${definition.members[from].path}.`); return; }
    if (drag.kind === "type") { const nested = model.udtDefinitions.find(item => definitionKey(item) === drag.path); if (!nested) throw new Error("The dragged type is no longer available."); let next = addNestedModelType(definition, nested, model.udtDefinitions); if (at !== undefined) next = reorderModelMember(next, next.members.length - 1, at); changeType(next); announce(`Nested ${drag.path}.`); return; }
    if (drag.kind === "folder") { const candidates = folderDropCandidates(drag.path, sourceTags, definition.members); if (!candidates.tags.length) throw new Error("This folder contains no saved tags."); if (!candidates.limit) throw new Error("This model already has 128 fields. Remove a field before adding more."); if (candidates.requiresSelection) setFolder({ path: drag.path, at }); else addReferences(candidates.tags, drag.path, at); return; }
    const tag = sourceTags.find(item => item.path === drag.path); if (!tag) throw new Error("The dragged tag is no longer in the gateway definitions.");
    if (replace && at !== undefined) { const replacement = replaceModelReferenceTarget(definition.members[at], tag); const apply = () => { changeType({ ...definition, members: definition.members.map((member, index) => index === at ? replacement.member : member) }); announce(`Updated ${replacement.member.path}.${replacement.warnings.join(" ")}`); }; if (replacement.requiresTypeConfirmation) setConfirm({ title: "Change reference data type?", description: `${definition.members[at].path}: ${definition.members[at].dataType || "Unknown"} → ${replacement.member.dataType || "Unknown"}. Existing bindings may need review.`, model, apply }); else apply(); }
    else addReferences([tag], undefined, at);
  }); }
  function addInstances(instances: ModelInstance[]) { if (model.instances.length + instances.length > 2000) throw new Error("The gateway supports at most 2,000 equipment items."); const paths = new Set(model.instances.map(item => item.path)); for (const instance of instances) { if (paths.has(instance.path)) throw new Error(`Equipment already exists at ${instance.path}. Choose a different location.`); paths.add(instance.path); } onChange({ ...model, instances: [...model.instances, ...instances] }); announce(`Added ${instances.length} draft equipment item${instances.length === 1 ? "" : "s"}.`); }
  function folderInstance(path: string) { attempt(() => { if (!definition) throw new Error("Choose a model with a machine parameter first."); addInstances([modelInstanceFromFolder(definition, path, model.instances.find(item => item.definitionId === definition.id))]); showMachines(); }); }
  function findFolders() { attempt(() => { if (!definition) return; const inferred = selectedFolder && inferModelParameterization(definition, selectedFolder, sourceTags); if (inferred) { showMachines(); setSuggestionOffer({ typeKey: selectedType, value: inferred }); announce("Matching folders are listed under Similar equipment."); return; } const found = offerModelParameterization(definition, sourceTags); if (found) { setOffer({ typeKey: selectedType, value: found }); return; } setFindFolder(true); }); }
  function requestRemove(title: string, description: string, apply: () => void) { setConfirm({ title, description, model, apply }); }
  const actions = { changeType, newType, editVersion, drop, folderInstance, findFolders, requestRemove, attempt };
  useBuilderContext(props, definition, selection, resolution, setSelection);
  const drawer = definition && selection ? <BuilderSelection disabled={props.disabled} key={`${selection.kind}-${selection.index}-${selectedType}`} selection={selection} definition={definition} model={model} tags={sourceTags} connections={props.connections} saved={saved} onClose={() => setSelection(undefined)} onChangeType={next => attempt(() => changeType(next))} onChange={onChange} onRemove={(title, apply) => requestRemove(title, "This removes the selected item from your draft. Review changes before saving.", () => { apply(); setSelection(undefined); })} /> : undefined;
  return <div className="model-builder" ref={surface}><ModelBuilderToolbar types={model.udtDefinitions} savedTypes={props.savedModel.udtDefinitions} selected={selectedType} disabled={props.disabled} libraryOpen={libraryOpen} onToggleLibrary={() => showLibrary(!libraryOpen)} onSelect={pickType} onAdd={drag => drop(drag)} />
    {!model.udtDefinitions.length ? <div className="model-builder-welcome"><BuilderShellController {...props} saved={false} setSelection={setSelection} actions={actions} announce={announce} /></div> : <ModelBuilderPanels showLibrary={libraryOpen} onCloseLibrary={() => showLibrary(false)} library={<ModelBuilderLibrary tags={sourceTags} values={props.tags} editable={!saved} disabled={props.disabled} selectedType={selectedType} usedTargets={usedTargets} onAdd={drag => drop(drag)} onFolderInstance={folderInstance} onSelectFolder={setSelectedFolder} />} shell={<BuilderShellController {...props} definition={definition} saved={saved} selection={selection} setSelection={setSelection} actions={actions} announce={announce} />} instances={definition ? <ModelBuilderInstances model={model} savedModel={props.savedModel} liveTags={props.tags} onIssues={props.onIssues} onVerify={props.onVerify} fromAskSpark={props.fromAskSpark} definition={definition} tags={sourceTags} suggestions={suggestions} onChange={onChange} onEdit={index => setSelection({ kind: "instance", index })} onFolder={folderInstance} onFindFolders={findFolders} onSuggest={items => attempt(() => { if (!activeOffer) return; const first = model.instances.find(item => item.definitionId === definition.id && item.version === definition.version); addInstances(items.map(item => suggestedModelInstance(definition, activeOffer, item, first))); })} onAnnounce={announce} onResolution={handleResolution} selectedPath={selection?.kind === "instance" ? model.instances[selection.index]?.path : undefined} /> : <div className="model-equipment-empty"><strong>Your machines will go here</strong><p>Create a model first. Then add equipment and choose the data for each machine.</p><small>Example: Press model → Press01, Press02, Press03</small></div>} drawer={drawer} />}
    <p className="model-builder-status" role="status" aria-live="polite">{message || "Changes stay in your draft until you choose Review & apply."}</p>
    {offer && offer.typeKey === selectedType && definition && <ParameterizeDialog offer={offer.value} onClose={() => { setOffer(undefined); announce("Kept the current tag paths. You can choose Reuse with other machines from the model menu later."); }} onAccept={name => { if (saved) throw new Error("Edit a new model version first."); const result = applyModelParameterization(definition, offer.value, name); if (model.instances.some(item => item.path === result.instance.path) || model.instances.length >= 2000) throw new Error("The first equipment location already exists, or the 2,000-item equipment limit is reached."); onChange({ ...model, udtDefinitions: model.udtDefinitions.map(item => definitionKey(item) === selectedType ? result.definition : item), instances: [...model.instances, result.instance] }); setSuggestionOffer({ typeKey: selectedType, value: result.offer }); showMachines(); setOffer(undefined); announce(`Added {${name}} as a reusable value and created the first equipment item: ${result.instance.path}.`); }} />}
    {folder && definition && <FolderSelection tags={folderDropCandidates(folder.path, sourceTags, definition.members).tags} limit={128 - definition.members.length} onClose={() => setFolder(undefined)} onAdd={tags => { addReferences(tags, folder.path, folder.at); setFolder(undefined); }} />}
    {confirm && <BuilderDialog title={confirm.title} onClose={() => setConfirm(undefined)}><p>{confirm.description}</p><footer><button type="button" className="button danger" onClick={() => { setConfirm(undefined); attempt(() => { if (confirm.model !== model) throw new Error("The draft changed. Review this action again."); confirm.apply(); }); }}>Confirm change</button></footer></BuilderDialog>}
    {findFolder && definition && <FindFolderDialog tags={sourceTags} initial={selectedFolder} onClose={() => setFindFolder(false)} onFind={path => { const found = inferModelParameterization(definition, path, sourceTags); if (!found) throw new Error("Choose a folder whose name fills one text parameter in this model’s linked tag paths."); setSelectedFolder(path); showMachines(); setSuggestionOffer({ typeKey: selectedType, value: found }); setFindFolder(false); announce(`Found ${found.suggestions.length} matching source folders.`); }} />}
  </div>;
}
const libraryKey = "sparkstudio.model-builder-library-open";
function readLibraryOpen(): boolean { try { return localStorage.getItem(libraryKey) === "true"; } catch { return false; } }
export function emptyBuilderModel(model: ModelPackage): ModelDefinition {
  const used = new Set(model.udtDefinitions.map(item => item.id)); let id = "NewModel", suffix = 2;
  while (used.has(id)) id = `NewModel${suffix++}`;
  return { id, version: 1, parameters: [], members: [] };
}
const itemIdentity = (instance: ModelInstance) => ({ id: instance.definitionId, version: instance.version });
function usedModelTargets(definition: ModelDefinition | undefined, model: ModelPackage, tags: ModelSourceTag[]) {
  const targets = new Set(definition?.members.filter(member => member.kind === "reference").map(member => member.target || ""));
  if (!definition) return targets;
  const instances = model.instances.filter(item => item.definitionId === definition.id && item.version === definition.version);
  for (const instance of resolveModelInstances(instances, model.udtDefinitions, tags, model.mappingProfiles)) for (const member of instance.members) if (member.target) targets.add(member.target);
  return targets;
}
function renameNestedPin(type: ModelDefinition, oldKey: string, next: ModelDefinition): ModelDefinition {
  if (definitionKey(next) === oldKey || !type.members.some(member => member.kind === "type" && `${member.definitionId}@${member.version}` === oldKey)) return type;
  return { ...type, members: type.members.map(member => member.kind === "type" && `${member.definitionId}@${member.version}` === oldKey ? { ...member, definitionId: next.id, version: next.version } : member) };
}
type Actions = { changeType: (next: ModelDefinition) => void; newType: () => void; editVersion: () => void; drop: (drag: BuilderDrag, at?: number, replace?: boolean) => void; folderInstance: (path: string) => void; findFolders: () => void; requestRemove: (title: string, description: string, apply: () => void) => void; attempt: (action: () => void) => void };
function BuilderShellController(props: ModelBuilderProps & { definition?: ModelDefinition; saved: boolean; selection?: Selection; setSelection: (value: Selection) => void; actions: Actions; announce: (message: string) => void }) {
  const { definition, actions, selection } = props;
  const addMember = (kind: ModelMember["kind"]) => actions.attempt(() => { if (!definition) return; let path = `${kind[0].toUpperCase() + kind.slice(1)}`, suffix = 2; while (definition.members.some(item => item.path === path)) path = `${kind}${suffix++}`; const member: ModelMember = { path, kind, dataType: "Double", ...(kind === "memory" ? { value: 0 } : kind === "expression" ? { expression: "", inputs: {} } : { connectionId: "", nodeId: "" }) }; actions.changeType({ ...definition, members: [...definition.members, member] }); props.setSelection({ kind: "member", index: definition.members.length }); });
  return <ModelBuilderShell value={definition} hasModels={props.model.udtDefinitions.length > 0} onUseStarter={props.onUseStarter} saved={props.saved} fromAskSpark={props.fromAskSpark?.includes(props.selectedType)} selectedMember={selection?.kind === "member" ? selection.index : undefined} highlightedParameter={selection?.kind === "parameter" ? definition?.parameters?.[selection.index]?.name : undefined} onChange={next => actions.attempt(() => actions.changeType(next))} onEditVersion={actions.editVersion} onMember={index => props.setSelection({ kind: "member", index })} onParameter={index => props.setSelection({ kind: "parameter", index })} onAddParameter={() => actions.attempt(() => { if (!definition) return; const parameters = definition.parameters || []; let name = "Parameter", suffix = 2; while (parameters.some(item => item.name === name)) name = `Parameter${suffix++}`; actions.changeType({ ...definition, parameters: [...parameters, { name, type: "String", required: true }] }); props.setSelection({ kind: "parameter", index: parameters.length }); })} onAddMember={addMember} onDrop={actions.drop} onParameterize={actions.findFolders} onNew={actions.newType} onAnnounce={props.announce} onRemoveType={() => definition && actions.requestRemove("Remove model version?", "Equipment using this version will need a different version or must also be removed.", () => { props.onChange({ ...props.model, udtDefinitions: props.model.udtDefinitions.filter(item => definitionKey(item) !== props.selectedType) }); props.onSelectType(""); })} />;
}
function useBuilderContext(props: ModelBuilderProps, definition: ModelDefinition | undefined, selection: Selection | undefined, resolution: string[], setSelection: (value: Selection) => void) {
  useEffect(() => { const target = props.focusTarget; if (!target || !definition) return; const instance = props.model.instances.findIndex(item => item.path === target || target.startsWith(item.path + "/")); if (instance >= 0) { setSelection({ kind: "instance", index: instance }); return; } const member = definition.members.findIndex(item => item.path === target || target.endsWith("/" + item.path)); if (member >= 0) setSelection({ kind: "member", index: member }); }, [props.focusTarget, definition, props.model.instances, setSelection]);
  useEffect(() => { const selected = selection?.kind === "instance" ? props.model.instances[selection.index]?.path : selection?.kind === "member" ? definition?.members[selection.index]?.path : selection?.kind === "parameter" ? definition?.parameters?.[selection.index]?.name : props.selectedType; props.onContextChange?.({ selection: selected ? [selected] : [], resolution }); }, [definition, selection, props.model.instances, props.selectedType, props.onContextChange, resolution]);
}
function BuilderSelection({ disabled, selection, definition, model, tags, connections, saved, onClose, onChangeType, onChange, onRemove }: { disabled?: boolean; selection: Selection; definition: ModelDefinition; model: ModelPackage; tags: ModelSourceTag[]; connections: Connection[]; saved: boolean; onClose: () => void; onChangeType: (next: ModelDefinition) => void; onChange: (next: ModelPackage) => void; onRemove: (title: string, apply: () => void) => void }) {
  if (selection.kind === "member") { const member = definition.members[selection.index]; if (!member) return null; return <BuilderDrawer disabled={disabled} title={member.path || "Field details"} onClose={onClose}><BuilderMemberEditor value={member} definition={definition} model={model} connections={connections} tags={tags} readOnly={saved} onChange={next => onChangeType({ ...definition, members: definition.members.map((item, index) => index === selection.index ? next : item) })} onRemove={() => onRemove("Remove field?", () => onChangeType({ ...definition, members: definition.members.filter((_item, index) => index !== selection.index) }))} /></BuilderDrawer>; }
  if (selection.kind === "parameter") { const parameter = definition.parameters?.[selection.index]; if (!parameter) return null; return <BuilderDrawer disabled={disabled} title={`Parameter ${parameter.name}`} onClose={onClose}><BuilderParameterEditor value={parameter} readOnly={saved} onChange={next => onChangeType({ ...definition, parameters: definition.parameters!.map((item, index) => index === selection.index ? next : item) })} onRemove={() => onRemove("Remove parameter?", () => onChangeType({ ...definition, parameters: definition.parameters!.filter((_item, index) => index !== selection.index) }))} /></BuilderDrawer>; }
  const instance = model.instances[selection.index]; if (!instance) return null; const pinned = model.udtDefinitions.find(item => item.id === instance.definitionId && item.version === instance.version), change = (next: ModelInstance) => onChange({ ...model, instances: model.instances.map((item, index) => index === selection.index ? next : item) });
  return <BuilderDrawer disabled={disabled} title={instance.path} onClose={onClose}><p>Uses {instance.definitionId} v{instance.version}. Change the settings for this piece of equipment.</p><label>Full location path<input value={instance.path} onChange={event => change({ ...instance, path: event.target.value })} /></label>{pinned && <><label>How this machine connects<select value={instance.mappingProfileId || ""} onChange={event => change({ ...instance, mappingProfileId: event.target.value || undefined })}><option value="">Sources from model definition</option>{(model.mappingProfiles || []).filter(profile => profile.definitionId === instance.definitionId && profile.version === instance.version).map(profile => <option key={profile.id}>{profile.id}</option>)}</select></label><ModelParameterValues parameters={pinned.parameters || []} values={instance.parameters} onChange={parameters => change({ ...instance, parameters })} /><details className="model-advanced"><summary>Advanced: customize fields for this equipment</summary><p className="model-help">Override a source or setting here when this machine differs from the model.</p><ModelOverrides value={instance} onChange={change} definition={pinned} definitions={model.udtDefinitions} /></details></>}<button type="button" className="button danger" onClick={() => onRemove("Remove equipment?", () => onChange({ ...model, instances: model.instances.filter((_item, index) => index !== selection.index) }))}>Remove equipment</button></BuilderDrawer>;
}
function ParameterizeDialog({ offer, onClose, onAccept }: { offer: ModelParameterizationOffer; onClose: () => void; onAccept: (name: string) => void }) {
  const [name, setName] = useState(offer.parameterName), [error, setError] = useState("");
  return <BuilderDialog title="Use this model for similar machines?" onClose={onClose}><p>We found {offer.suggestions.length} similar folders. Make <strong>{offer.sourceValue}</strong> a value you can change for each machine, instead of linking every machine to the same tags.</p><label>Name this reusable value<input value={name} onChange={event => setName(event.target.value)} /></label><p className="model-help">For example, fill in <code>{`{${name}}`}</code> with <strong>{offer.sourceValue}</strong> for your first machine. We will create that equipment item for you.</p><details className="model-advanced"><summary>See how the tag path changes</summary><p><code>{offer.root}</code> → <code>{offer.parent}/{`{${name}}`}</code></p></details>{error && <p role="alert" className="model-warning">{error}</p>}<footer><button type="button" className="button" onClick={onClose}>Keep these exact tags</button><button type="button" className="button primary" onClick={() => { try { onAccept(name); } catch (reason) { setError(reason instanceof Error ? reason.message : String(reason)); } }}>Make reusable & add equipment</button></footer></BuilderDialog>;
}
function FolderSelection({ tags, limit, onClose, onAdd }: { tags: ModelSourceTag[]; limit: number; onClose: () => void; onAdd: (tags: ModelSourceTag[]) => void }) {
  const [selected, setSelected] = useState(new Set<string>()), [search, setSearch] = useState(""), [page, setPage] = useState(0), matches = tags.filter(tag => tag.path.toLowerCase().includes(search.toLowerCase()));
  return <BuilderDialog title="Choose folder tags" onClose={onClose}><p>This folder has {tags.length} tags. Choose up to {limit} for this model.</p><label>Filter tags<input value={search} onChange={event => { setSearch(event.target.value); setPage(0); }} /></label><div className="model-folder-choices">{matches.slice(page * 100, page * 100 + 100).map(tag => <label className="model-checkbox" key={tag.path}><input type="checkbox" checked={selected.has(tag.path)} disabled={!selected.has(tag.path) && selected.size >= limit} onChange={event => setSelected(previous => { const next = new Set(previous); if (event.target.checked) next.add(tag.path); else next.delete(tag.path); return next; })} />{tag.path}</label>)}</div><footer><button type="button" className="button" disabled={!page} onClick={() => setPage(page - 1)}>Previous</button><button type="button" className="button" disabled={(page + 1) * 100 >= matches.length} onClick={() => setPage(page + 1)}>Next</button><button type="button" className="button primary" disabled={!selected.size} onClick={() => onAdd(tags.filter(tag => selected.has(tag.path)))}>Add {selected.size} selected tags</button></footer></BuilderDialog>;
}
function FindFolderDialog({ tags, initial, onClose, onFind }: { tags: ModelSourceTag[]; initial: string; onClose: () => void; onFind: (path: string) => void }) {
  const [path, setPath] = useState(initial), [error, setError] = useState("");
  const folders = useMemo(() => { const paths = new Set<string>(); for (const tag of tags) { let current = tag.path; while (current.includes("/")) { current = current.slice(0, current.lastIndexOf("/")); paths.add(current); } } return [...paths].sort(); }, [tags]);
  return <BuilderDialog title="Find matching source folders" onClose={onClose}><p>Choose the folder for one machine. We will look for other folders with the same fields and suggest more equipment.</p><label>Source folder<input list="model-find-source-folders" value={path} onChange={event => setPath(event.target.value)} /></label><datalist id="model-find-source-folders">{folders.filter(folder => folder.toLowerCase().includes(path.toLowerCase())).slice(0, 100).map(folder => <option key={folder} value={folder} />)}</datalist>{error && <p role="alert" className="model-warning">{error}</p>}<footer><button type="button" className="button primary" disabled={!path} onClick={() => { try { onFind(path); } catch (reason) { setError(reason instanceof Error ? reason.message : String(reason)); } }}>Find matching folders</button></footer></BuilderDialog>;
}
