import { useState } from "react";
import { definitionKey, type ModelPackage } from "./modelWorkspace";
import { downloadModelBundle, exportModelSelection, getModelDependencies, modelErrorText, type ModelDependencyGraph, type ModelExportResult } from "./modelOperationsApi";

export function ModelDependencyPanel({ model }: { model: ModelPackage }) {
  const [type, setType] = useState(""), [instance, setInstance] = useState(""), [query, setQuery] = useState(""), [graph, setGraph] = useState<ModelDependencyGraph>(), [error, setError] = useState(""), [busy, setBusy] = useState(false);
  async function load() { setBusy(true); setError(""); try { setGraph(await getModelDependencies(type, instance, query)); } catch (reason) { setError(modelErrorText(reason)); } finally { setBusy(false); } }
  const labels = new Map(graph?.nodes.map(node => [node.id, node.label]));
  return <section className="model-operation-panel"><h2>Dependencies</h2><p>Trace the connections and tags a model reads, the equipment that uses it, and the projects that depend on it.</p><div className="model-grid"><label>Model<select value={type} onChange={event => { setType(event.target.value); setGraph(undefined); }}><option value="">All models</option>{[...new Set(model.udtDefinitions.map(item => item.id))].map(id => <option key={id}>{id}</option>)}</select></label><label>Equipment<select value={instance} onChange={event => { setInstance(event.target.value); setGraph(undefined); }}><option value="">All equipment</option>{model.instances.map(item => <option key={item.path}>{item.path}</option>)}</select></label><label>Search<input value={query} onChange={event => { setQuery(event.target.value); setGraph(undefined); }} placeholder="Connection, tag, project or model" /></label></div><button type="button" className="button" disabled={busy} onClick={() => void load()}>{busy ? "Tracing…" : "Trace dependencies"}</button>{error && <p className="security-error" role="alert">{error}</p>}{graph && <><p>{graph.nodes.length} resources · {graph.edges.length} relationships{graph.truncated ? " · Results capped; narrow your selection." : ""}</p>{graph.issues.map((issue, index) => <p className="model-warning" key={index}>{issue.id}: {issue.message}</p>)}<div className="model-table-wrap"><table><thead><tr><th>Resource</th><th>Relationship</th><th>Dependency</th></tr></thead><tbody>{graph.edges.map((edge, index) => <tr key={index}><td>{labels.get(edge.from) || edge.from}</td><td>{edge.relation}</td><td>{labels.get(edge.to) || edge.to}</td></tr>)}</tbody></table></div><details><summary>All included resources</summary><ul>{graph.nodes.map(node => <li key={node.id}>{node.kind}: {node.label}</li>)}</ul></details></>}</section>;
}
export function ModelSelectiveExportPanel({ model }: { model: ModelPackage }) {
  const [types, setTypes] = useState<string[]>([]), [instances, setInstances] = useState<string[]>([]), [sources, setSources] = useState(true), [result, setResult] = useState<ModelExportResult>(), [error, setError] = useState(""), [busy, setBusy] = useState(false), [filter, setFilter] = useState("");
  const toggle = (items: string[], key: string, checked: boolean) => checked ? [...items, key] : items.filter(item => item !== key);
  async function prepare() { setBusy(true); setError(""); try { setResult(await exportModelSelection(types, instances, sources)); } catch (reason) { setError(modelErrorText(reason)); } finally { setBusy(false); } }
  return <section className="model-operation-panel"><h2>Export selected models and equipment</h2><p>Dependencies are included automatically. Connection credentials and external device setup stay on their gateway.</p><label>Find resources<input value={filter} onChange={event => setFilter(event.target.value)} /></label><div className="model-grid"><section><h3>Model versions</h3><div className="model-operation-list">{model.udtDefinitions.filter(item => definitionKey(item).toLowerCase().includes(filter.toLowerCase())).map(item => <label className="model-checkbox" key={definitionKey(item)}><input type="checkbox" checked={types.includes(definitionKey(item))} onChange={event => { setTypes(toggle(types, definitionKey(item), event.target.checked)); setResult(undefined); }} />{item.id} v{item.version}</label>)}</div></section><section><h3>Equipment</h3><div className="model-operation-list">{model.instances.filter(item => item.path.toLowerCase().includes(filter.toLowerCase())).map(item => <label className="model-checkbox" key={item.path}><input type="checkbox" checked={instances.includes(item.path)} onChange={event => { setInstances(toggle(instances, item.path, event.target.checked)); setResult(undefined); }} />{item.path}</label>)}</div></section></div><label className="model-checkbox"><input type="checkbox" checked={sources} onChange={event => { setSources(event.target.checked); setResult(undefined); }} />Include authored source tags and their dependencies</label><button type="button" className="button" disabled={busy || !types.length && !instances.length} onClick={() => void prepare()}>{busy ? "Preparing…" : "Preview export"}</button>{error && <p className="security-error" role="alert">{error}</p>}{result && <div className="model-card"><h3>Export contents</h3><p>{Object.entries(result.summary).map(([kind, count]) => `${count} ${kind}`).join(" · ")}</p>{result.externalDependencies.length > 0 && <><h4>Set up separately on the receiving gateway</h4><ul>{result.externalDependencies.map((item, index) => <li key={index}>{item.kind}: {item.id} · {item.reason}</li>)}</ul></>}<button type="button" className="button primary" onClick={() => downloadModelBundle(result)}>Download model bundle</button><p>Use Import into draft on the receiving gateway, review its dependencies, then Review changes.</p></div>}</section>;
}
