import type { TranslationCatalog } from "./types";
const languages: Record<string, Record<string, string>> = {
  es: { communicationLost: "Comunicación perdida", staleValues: "Los valores pueden estar desactualizados", healthy: "Datos en vivo correctos", connected: "Gateway conectado", actionFailed: "La acción falló.", actionCompleted: "Acción completada.", retry: "Reintentar", dismiss: "Cerrar aviso", fullscreen: "Pantalla completa", exitFullscreen: "Salir de pantalla completa", goToScreen: "Ir a pantalla", language: "Idioma", loading: "Abriendo la aplicación", applicationUnavailable: "Aplicación no disponible", projectUnavailable: "Proyecto no disponible", loadVersion: "Cargar nueva versión", communicationDetail: "Los valores mostrados son los últimos recibidos y pueden estar desactualizados. Reconexión automática en curso." },
  fr: { communicationLost: "Communication perdue", staleValues: "Les valeurs peuvent être obsolètes", healthy: "Données en direct correctes", connected: "Passerelle connectée", actionFailed: "Échec de l’action.", actionCompleted: "Action terminée.", retry: "Réessayer", dismiss: "Fermer le message", fullscreen: "Plein écran", exitFullscreen: "Quitter le plein écran", goToScreen: "Aller à l’écran", language: "Langue", loading: "Ouverture de l’application", applicationUnavailable: "Application indisponible", projectUnavailable: "Projet indisponible", loadVersion: "Charger la nouvelle version", communicationDetail: "Les valeurs affichées sont les dernières reçues et peuvent être obsolètes. Reconnexion automatique en cours." },
  de: { communicationLost: "Verbindung unterbrochen", staleValues: "Werte sind möglicherweise veraltet", healthy: "Livedaten aktuell", connected: "Gateway verbunden", actionFailed: "Aktion fehlgeschlagen.", actionCompleted: "Aktion abgeschlossen.", retry: "Erneut versuchen", dismiss: "Hinweis schließen", fullscreen: "Vollbild", exitFullscreen: "Vollbild beenden", goToScreen: "Bildschirm öffnen", language: "Sprache", loading: "Anwendung wird geöffnet", applicationUnavailable: "Anwendung nicht verfügbar", projectUnavailable: "Projekt nicht verfügbar", loadVersion: "Neue Version laden", communicationDetail: "Die angezeigten Werte wurden zuletzt empfangen und können veraltet sein. Die Verbindung wird automatisch wiederhergestellt." },
  it: { communicationLost: "Comunicazione interrotta", staleValues: "I valori potrebbero non essere aggiornati", healthy: "Dati in tempo reale disponibili", connected: "Gateway connesso", actionFailed: "Azione non riuscita.", actionCompleted: "Azione completata.", retry: "Riprova", dismiss: "Chiudi avviso", fullscreen: "Schermo intero", exitFullscreen: "Esci da schermo intero", goToScreen: "Vai alla schermata", language: "Lingua", loading: "Apertura dell’applicazione", applicationUnavailable: "Applicazione non disponibile", projectUnavailable: "Progetto non disponibile", loadVersion: "Carica nuova versione", communicationDetail: "I valori visualizzati sono gli ultimi ricevuti e potrebbero non essere aggiornati. Riconnessione automatica in corso." },
  pt: { communicationLost: "Comunicação perdida", staleValues: "Os valores podem estar desatualizados", healthy: "Dados em tempo real disponíveis", connected: "Gateway conectado", actionFailed: "A ação falhou.", actionCompleted: "Ação concluída.", retry: "Tentar novamente", dismiss: "Fechar aviso", fullscreen: "Tela cheia", exitFullscreen: "Sair da tela cheia", goToScreen: "Ir para tela", language: "Idioma", loading: "Abrindo o aplicativo", applicationUnavailable: "Aplicativo indisponível", projectUnavailable: "Projeto indisponível", loadVersion: "Carregar nova versão", communicationDetail: "Os valores exibidos são os últimos recebidos e podem estar desatualizados. Reconexão automática em andamento." },
};
/** Project translations can override runtime.<key>; missing strings fall back to built-ins then English. */
export function runtimeText(catalog: TranslationCatalog | undefined, locale: string, key: string, fallback: string): string {
  const entry = catalog?.messages[`runtime.${key}`];
  return entry?.[locale] ?? languages[locale.split("-")[0]]?.[key] ?? entry?.[catalog?.defaultLocale ?? "en"] ?? fallback;
}
