// Complexity ceilings are reviewed source policy, never regenerated by a build.
export const policyVersion = 1;
export const csharpMetric = {
  name: 'McCabe cyclomatic complexity (syntax-based)', version: 1, base: 1,
  decisions: ['if', 'for', 'foreach', 'while', 'do-while', 'catch', 'conditional expression',
    'non-default switch case', 'non-default switch arm', 'when guard', '&&', '||', '??', 'and pattern', 'or pattern'],
  exclusions: ['nested executable units (reported separately)', 'optional chaining', 'else',
    'default switch clauses and discard arms', 'logical assignment operators', 'type syntax'],
};
export const pythonMetric = {
  name: 'McCabe cyclomatic complexity (syntax-based)', version: 1, base: 1,
  decisions: ['if', 'conditional expression', 'for', 'async-for', 'while', 'except', 'assert',
    'and', 'or', 'chained comparison', 'comprehension for', 'comprehension filter',
    'non-default match case', 'match guard', 'or pattern'],
  exclusions: ['nested functions/lambdas (reported separately)', 'else', 'finally', 'with',
    'irrefutable match case', 'type annotations'],
};

export const functionKey = item => JSON.stringify([item.language, item.file, item.name, item.occurrence]);

export function checkPolicy(reports, baseline) {
  if (baseline.version !== policyVersion || baseline.maximumNewComplexity !== 20 || !Array.isArray(baseline.exceptions))
    throw new Error('Unsupported complexity policy; the reviewed threshold is 20.');
  const expectedLanguages = ['csharp', 'typescript', 'python'];
  if (reports.length !== expectedLanguages.length || !expectedLanguages.every(language => reports.some(report => report.language === language)))
    throw new Error('All three application languages must be analyzed.');
  for (const report of reports) {
    if (!report.files.length || !report.functions.length || JSON.stringify(report.metric) !== JSON.stringify(baseline.metrics[report.language]))
      throw new Error(`Incomplete or incompatible ${report.language} complexity report.`);
  }
  const ceilings = new Map();
  for (const entry of baseline.exceptions) {
    if (!expectedLanguages.includes(entry.language) || typeof entry.file !== 'string' || !entry.file
      || typeof entry.name !== 'string' || !entry.name || !Number.isInteger(entry.occurrence) || entry.occurrence < 1
      || !Number.isInteger(entry.ceiling) || entry.ceiling <= baseline.maximumNewComplexity)
      throw new Error('Invalid reviewed complexity exception.');
    const key = functionKey(entry);
    if (ceilings.has(key)) throw new Error('Duplicate reviewed complexity exception.');
    ceilings.set(key, entry.ceiling);
  }
  const functions = reports.flatMap(report => report.functions.map(item => ({ ...item, language: report.language })));
  const seen = new Set();
  const violations = [], reductions = [];
  for (const item of functions) {
    const key = functionKey(item);
    if (seen.has(key) || !Number.isInteger(item.complexity) || item.complexity < 1)
      throw new Error('Invalid or duplicate analyzed complexity unit.');
    seen.add(key);
    const ceiling = ceilings.get(key) ?? baseline.maximumNewComplexity;
    if (item.complexity > ceiling) violations.push({ ...item, ceiling, reason: ceilings.has(key) ? 'existing hotspot increased' : 'new hotspot' });
    if (ceilings.has(key) && item.complexity < ceiling) reductions.push({ ...item, ceiling });
  }
  return { violations, reductions, removedExceptions: baseline.exceptions.filter(entry => !seen.has(functionKey(entry))) };
}
